#ifndef KMAP_H
#define KMAP_H

#define        kmapSYSREQ              0
#define        kmapCAPSLOCK            1
#define        kmapNUMLOCK             2
#define        kmapSCROLLLOCK          3
#define        kmapLEFTCTRL            4
#define        kmapLEFTALT             5
#define        kmapLEFTSHIFT           6
#define        kmapRIGHTCTRL           7
#define        kmapRIGHTALT            8
#define        kmapRIGHTSHIFT          9
#define        kmapESC                 10
#define        kmapBACKSPACE           11
#define        kmapENTER               12
#define        kmapSPACE               13
#define        kmapTAB                 14
#define        kmapF1                  15
#define        kmapF2                  16
#define        kmapF3                  17
#define        kmapF4                  18
#define        kmapF5                  19
#define        kmapF6                  20
#define        kmapF7                  21
#define        kmapF8                  22
#define        kmapF9                  23
#define        kmapF10                 24
#define        kmapF11                 25
#define        kmapF12                 27
#define        kmapA                   28
#define        kmapB                   29
#define        kmapC                   30
#define        kmapD                   31
#define        kmapE                   32
#define        kmapF                   33
#define        kmapG                   34
#define        kmapH                   35
#define        kmapI                   36
#define        kmapJ                   37
#define        kmapK                   38
#define        kmapL                   39
#define        kmapM                   40
#define        kmapN                   41
#define        kmapO                   42
#define        kmapP                   43
#define        kmapQ                   44
#define        kmapR                   45
#define        kmapS                   46
#define        kmapT                   47
#define        kmapU                   48
#define        kmapV                   49
#define        kmapW                   50
#define        kmapX                   51
#define        kmapY                   52
#define        kmapZ                   53
#define        kmap1                   54
#define        kmap2                   55
#define        kmap3                   56
#define        kmap4                   57
#define        kmap5                   58
#define        kmap6                   59
#define        kmap7                   60
#define        kmap8                   61
#define        kmap9                   62
#define        kmap0                   63
#define        kmapMINUS               64
#define        kmapEQUAL               65
#define        kmapLBRACKET            66
#define        kmapRBRACKET            67
#define        kmapSEMICOLON           68
#define        kmapTICK                69
#define        kmapAPOSTROPHE          70
#define        kmapBACKSLASH           71
#define        kmapCOMMA               72
#define        kmapPERIOD              73
#define        kmapSLASH               74
#define        kmapINS                 75
#define        kmapDEL                 76
#define        kmapHOME                77
#define        kmapEND                 78
#define        kmapPGUP                79
#define        kmapPGDN                80
#define        kmapLARROW              81
#define        kmapRARROW              82
#define        kmapUARROW              83
#define        kmapDARROW              84
#define        kmapKEYPAD0             85
#define        kmapKEYPAD1             86
#define        kmapKEYPAD2             87
#define        kmapKEYPAD3             88
#define        kmapKEYPAD4             89
#define        kmapKEYPAD5             90
#define        kmapKEYPAD6             91
#define        kmapKEYPAD7             92
#define        kmapKEYPAD8             93
#define        kmapKEYPAD9             94
#define        kmapKEYPADDEL           95
#define        kmapKEYPADSTAR          96
#define        kmapKEYPADMINUS         97
#define        kmapKEYPADPLUS          98
#define        kmapKEYPADENTER         99
#define        kmapCTRLPRTSC           100
#define        kmapSHIFTPRTSC          101
#define        kmapKEYPADSLASH         102

#endif /* KMAP_H*/



