
#ifndef __RB_KEYMAP_H__
#define __RB_KEYMAP_H__


/* KEYMAPS */
#if CONFIG_KEYPAD == IRIVER_H100_PAD
#define CONSOLE_SELECT  BUTTON_OFF
#define JOY_TRIGGER     BUTTON_SELECT
#define PLUGIN_QUIT     BUTTON_MODE
#define CONSOLE_RESET   BUTTON_REC

#elif CONFIG_KEYPAD == IRIVER_H300_PAD
#define CONSOLE_SELECT BUTTON_MODE
#define JOY_TRIGGER    BUTTON_SELECT
#define PLUGIN_QUIT    BUTTON_OFF
#define CONSOLE_RESET  BUTTON_ON

#elif CONFIG_KEYPAD == RECORDER_PAD
#define CONSOLE_RESET  BUTTON_F1
#define CONSOLE_SELECT BUTTON_F2
#define JOY_TRIGGER    BUTTON_PLAY
#define PLUGIN_QUIT    BUTTON_OFF

#elif CONFIG_KEYPAD == IPOD_4G_PAD
#define HOLD_IS_MENU
#define JOY_UP          BUTTON_MENU
#define JOY_DOWN        BUTTON_PLAY
#define JOY_TRIGGER     BUTTON_SELECT

#elif CONFIG_KEYPAD == IRIVER_IFP7XX_PAD
#define CONSOLE_SELECT   BUTTON_PLAY
#define CONSOLE_RESET    BUTTON_MODE
#define JOY_TRIGGER      BUTTON_SELECT
#define PLUGIN_QUIT      BUTTON_EQ

#elif CONFIG_KEYPAD == GIGABEAT_PAD
#define CONSOLE_RESET   BUTTON_VOL_UP
#define CONSOLE_SELECT  BUTTON_VOL_DOWN
#define JOY_TRIGGER     BUTTON_SELECT
#define PLUGIN_QUIT     BUTTON_MENU

#elif CONFIG_KEYPAD == SANSA_E200_PAD
#define JOY_TRIGGER     BUTTON_SELECT
#define PLUGIN_QUIT     BUTTON_POWER
#define CONSOLE_RESET   BUTTON_REC

#elif CONFIG_KEYPAD == SANSA_FUZE_PAD
#define JOY_TRIGGER     BUTTON_SELECT
#define PLUGIN_QUIT     BUTTON_POWER
#define CONSOLE_RESET   BUTTON_HOME

#elif CONFIG_KEYPAD == SANSA_C200_PAD
#define JOY_TRIGGER     BUTTON_SELECT
#define CONSOLE_SELECT  BUTTON_VOL_UP
#define PLUGIN_QUIT     BUTTON_POWER
#define CONSOLE_RESET   BUTTON_VOL_DOWN

#elif CONFIG_KEYPAD == SANSA_CLIP_PAD
#define JOY_TRIGGER     BUTTON_SELECT
#define CONSOLE_SELECT  BUTTON_VOL_UP
#define CONSOLE_RESET   BUTTON_VOL_DOWN
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == IAUDIO_X5M5_PAD
#define CONSOLE_SELECT  BUTTON_REC
#define JOY_TRIGGER     BUTTON_SELECT
#define CONSOLE_RESET   BUTTON_PLAY
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == IRIVER_H10_PAD
#define JOY_UP          BUTTON_SCROLL_UP
#define JOY_DOWN        BUTTON_SCROLL_DOWN
#define JOY_TRIGGER     BUTTON_PLAY
#define CONSOLE_SELECT  BUTTON_FF
#define CONSOLE_RESET   BUTTON_REW
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == MROBE500_PAD
#define PLUGIN_QUIT    BUTTON_POWER

#elif CONFIG_KEYPAD == COWON_D2_PAD
#define JOY_TRIGGER     BUTTON_PLUS
#define CONSOLE_RESET   BUTTON_MINUS
#define PLUGIN_QUIT     BUTTON_MENU

#elif CONFIG_KEYPAD == GIGABEAT_S_PAD
#define CONSOLE_SELECT  BUTTON_MENU
#define CONSOLE_RESET   BUTTON_PLAY
#define JOY_TRIGGER     BUTTON_SELECT
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == CREATIVEZVM_PAD
#define CONSOLE_RESET   BUTTON_CUSTOM
#define CONSOLE_SELECT  BUTTON_PLAY
#define JOY_TRIGGER     BUTTON_SELECT
#define PLUGIN_QUIT     BUTTON_MENU

#elif CONFIG_KEYPAD == CREATIVE_ZEN_PAD
#define CONSOLE_RESET   BUTTON_MENU
#define CONSOLE_SELECT  BUTTON_PLAYPAUSE
#define JOY_TRIGGER     BUTTON_SELECT
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == CREATIVE_ZENXFI2_PAD
#define CONSOLE_RESET   BUTTON_TOPRIGHT
#define CONSOLE_SELECT  BUTTON_TOPLEFT
#define JOY_TRIGGER     BUTTON_CENTER
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == CREATIVE_ZENXFI3_PAD
#define CONSOLE_RESET   BUTTON_VOL_DOWN
#define CONSOLE_SELECT  BUTTON_VOL_UP
#define JOY_TRIGGER     BUTTON_PLAY
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == PHILIPS_HDD1630_PAD
#define CONSOLE_RESET   BUTTON_VOL_UP
#define CONSOLE_SELECT  BUTTON_VOL_DOWN
#define JOY_TRIGGER     BUTTON_SELECT
#define PLUGIN_QUIT     BUTTON_MENU

#elif CONFIG_KEYPAD == PHILIPS_HDD6330_PAD
#define CONSOLE_RESET  BUTTON_VOL_UP
#define CONSOLE_SELECT BUTTON_VOL_DOWN
#define JOY_TRIGGER    BUTTON_PLAY
#define PLUGIN_QUIT    BUTTON_MENU

#elif CONFIG_KEYPAD == PHILIPS_SA9200_PAD
#define JOY_TRIGGER    BUTTON_PLAY
#define CONSOLE_SELECT BUTTON_VOL_DOWN
#define PLUGIN_QUIT    BUTTON_MENU
#define CONSOLE_RESET  BUTTON_VOL_UP

#elif CONFIG_KEYPAD == ONDAVX747_PAD
#define JOY_TRIGGER    BUTTON_VOL_UP
#define CONSOLE_RESET  BUTTON_VOL_DOWN
#define PLUGIN_QUIT    BUTTON_MENU

#elif CONFIG_KEYPAD == ONDAVX777_PAD
#define PLUGIN_QUIT    BUTTON_POWER

#elif CONFIG_KEYPAD == IRIVER_H10_PAD
#define JOY_TRIGGER     BUTTON_PLAY
#define CONSOLE_RESET   BUTTON_FFWD
#define PLUGIN_QUIT     BUTTON_REW

#elif CONFIG_KEYPAD == SAMSUNG_YH92X_PAD
#define JOY_TRIGGER     BUTTON_FFWD
#define CONSOLE_SELECT  BUTTON_PLAY
#define CONSOLE_RESET   BUTTON_REW
#define PLUGIN_QUIT     BUTTON_REC_SW_ON
#define HOLD_IS_MENU

#elif CONFIG_KEYPAD == SAMSUNG_YH820_PAD
#define JOY_TRIGGER     BUTTON_FFWD
#define CONSOLE_SELECT  BUTTON_PLAY
#define CONSOLE_RESET   BUTTON_REC
#define PLUGIN_QUIT     BUTTON_REW
#define HOLD_IS_MENU

#elif CONFIG_KEYPAD == PBELL_VIBE500_PAD
#define JOY_UP          BUTTON_OK
#define JOY_DOWN        BUTTON_CANCEL
#define JOY_LEFT        BUTTON_PREV
#define JOY_RIGHT       BUTTON_NEXT
#define JOY_TRIGGER     BUTTON_MENU
#define CONSOLE_SELECT  BUTTON_PLAY
#define CONSOLE_RESET   BUTTON_POWER
#define PLUGIN_QUIT     BUTTON_REC

#elif CONFIG_KEYPAD == MPIO_HD300_PAD
#define JOY_LEFT       BUTTON_REW
#define JOY_RIGHT      BUTTON_FF
#define JOY_TRIGGER    BUTTON_PLAY
#define CONSOLE_SELECT BUTTON_REC
#define CONSOLE_RESET  BUTTON_ENTER
#define PLUGIN_QUIT    BUTTON_MENU

#elif CONFIG_KEYPAD == SANSA_FUZEPLUS_PAD
#define CONSOLE_RESET  BUTTON_BOTTOMRIGHT
#define CONSOLE_SELECT BUTTON_BOTTOMLEFT
#define JOY_TRIGGER    BUTTON_VOL_UP
#define PLUGIN_QUIT    BUTTON_POWER

#elif CONFIG_KEYPAD == SANSA_CONNECT_PAD
#define CONSOLE_RESET  BUTTON_VOL_UP
#define CONSOLE_SELECT BUTTON_VOL_DOWN
#define PLUGIN_QUIT    BUTTON_NEXT
#define JOY_TRIGGER    BUTTON_SELECT

#elif CONFIG_KEYPAD == SAMSUNG_YPR0_PAD
#define JOY_TRIGGER    BUTTON_SELECT
#define CONSOLE_SELECT BUTTON_BACK
#define CONSOLE_RESET  BUTTON_USER
#define PLUGIN_QUIT    BUTTON_MENU

#elif CONFIG_KEYPAD == HM801_PAD
#define CONSOLE_SELECT BUTTON_NEXT
#define CONSOLE_RESET  BUTTON_PLAY
#define JOY_TRIGGER    BUTTON_SELECT
#define PLUGIN_QUIT    BUTTON_POWER

#elif CONFIG_KEYPAD == MROBE500_PAD
#define JOY_UP          BUTTON_RC_VOL_UP
#define JOY_DOWN        BUTTON_RC_VOL_DOWN
#define JOY_LEFT        BUTTON_RC_REW
#define JOY_RIGHT       BUTTON_RC_FF
#define JOY_TRIGGER     BUTTON_RC_PLAY
#define CONSOLE_RESET   BUTTON_RC_DOWN
#define CONSOLE_SELECT  BUTTON_RC_MODE
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == MROBE100_PAD
#define JOY_TRIGGER     BUTTON_SELECT
#define CONSOLE_SELECT  BUTTON_MENU
#define CONSOLE_RESET   BUTTON_PLAY
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == SONY_NWZ_PAD
#define JOY_TRIGGER     BUTTON_PLAY
#define PLUGIN_QUIT     BUTTON_BACK

#elif CONFIG_KEYPAD == DX50_PAD
#define JOY_TRIGGER     BUTTON_VOL_UP
#define CONSOLE_RESET   BUTTON_VOL_DOWN
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == AGPTEK_ROCKER_PAD
#define JOY_TRIGGER     BUTTON_SELECT
#define CONSOLE_SELECT  BUTTON_VOLUP
#define CONSOLE_RESET   BUTTON_VOLDOWN
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == XDUOO_X3_PAD
#define JOY_UP          BUTTON_PREV
#define JOY_DOWN        BUTTON_NEXT
#define JOY_TRIGGER     BUTTON_HOME
#define CONSOLE_RESET   BUTTON_VOL_DOWN
#define CONSOLE_SELECT  BUTTON_VOL_UP
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == IHIFI_770_PAD
#define JOY_UP          BUTTON_PREV
#define JOY_DOWN        BUTTON_NEXT
#define JOY_TRIGGER     BUTTON_PLAY
#define CONSOLE_RESET   BUTTON_VOL_DOWN
#define CONSOLE_SELECT  BUTTON_VOL_UP
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == IHIFI_800_PAD
#define JOY_UP          BUTTON_PREV
#define JOY_DOWN        BUTTON_NEXT
#define JOY_TRIGGER     BUTTON_PLAY
#define CONSOLE_RESET   BUTTON_VOL_DOWN
#define CONSOLE_SELECT  BUTTON_VOL_UP
#define PLUGIN_QUIT     BUTTON_POWER

#else
#error No Keymap Defined!
#endif


#ifdef HAVE_TOUCHSCREEN
/* define standard touchscreen buttons */
#ifndef JOY_LEFT
#define JOY_LEFT        BUTTON_MIDLEFT
#endif
#ifndef JOY_RIGHT
#define JOY_RIGHT       BUTTON_MIDRIGHT
#endif
#ifndef JOY_UP
#define JOY_UP          BUTTON_TOPMIDDLE
#endif
#ifndef JOY_DOWN
#define JOY_DOWN        BUTTON_BOTTOMMIDDLE
#endif
#ifndef JOY_TRIGGER
#define JOY_TRIGGER     BUTTON_BOTTOMLEFT
#endif
#ifndef CONSOLE_SELECT
#define CONSOLE_SELECT  BUTTON_BOTTOMRIGHT
#endif
#ifndef PLUGIN_QUIT
#define PLUGIN_QUIT     BUTTON_TOPLEFT
#endif

#else /* HAVE_TOUCHSCREEN */
/* define standard (non-touch) directional buttons */
#ifndef JOY_LEFT
#define JOY_LEFT    BUTTON_LEFT
#endif
#ifndef JOY_RIGHT
#define JOY_RIGHT   BUTTON_RIGHT
#endif
#ifndef JOY_UP
#define JOY_UP      BUTTON_UP
#endif
#ifndef JOY_DOWN
#define JOY_DOWN    BUTTON_DOWN
#endif

#endif /* !HAVE_TOUCHSCREEN */


#endif
