#ifndef RBCONFIG_H
#define RBCONFIG_H

#include <plugin.h>
extern const struct plugin_api * rb;

/* KEYMAPS */
#ifdef HAVE_TOUCHSCREEN
#define JOY_LEFT    BUTTON_MIDLEFT
#define JOY_RIGHT   BUTTON_MIDRIGHT
#else
#define JOY_LEFT    BUTTON_LEFT
#define JOY_RIGHT   BUTTON_RIGHT
#endif

#if CONFIG_KEYPAD == IRIVER_H100_PAD
#define JOY_UP          BUTTON_UP
#define JOY_DOWN        BUTTON_DOWN
#define CONSOLE_OPTION  BUTTON_OFF
#define JOY_TRIGGER     BUTTON_SELECT
#define PLUGIN_QUIT     BUTTON_MODE
#define CONSOLE_RESET   BUTTON_NONE

#elif CONFIG_KEYPAD == IRIVER_H300_PAD
#define JOY_UP         BUTTON_UP
#define JOY_DOWN       BUTTON_DOWN
#define CONSOLE_OPTION BUTTON_MODE
#define JOY_TRIGGER    BUTTON_SELECT
#define PLUGIN_QUIT    BUTTON_OFF
#define CONSOLE_RESET  BUTTON_NONE

#elif CONFIG_KEYPAD == RECORDER_PAD
#define JOY_UP         BUTTON_UP
#define JOY_DOWN       BUTTON_DOWN
#define CONSOLE_RESET  BUTTON_F1
#define CONSOLE_OPTION BUTTON_F2
#define JOY_TRIGGER    BUTTON_PLAY
#define PLUGIN_QUIT    BUTTON_OFF

#elif CONFIG_KEYPAD == IPOD_4G_PAD
#define JOY_UP          BUTTON_MENU
#define JOY_DOWN        BUTTON_PLAY
#define CONSOLE_OPTION  BUTTON_NONE
#define JOY_TRIGGER     BUTTON_SELECT
#define CONSOLE_RESET   BUTTON_NONE
#define PLUGIN_QUIT     (BUTTON_SELECT | BUTTON_REPEAT)

#elif CONFIG_KEYPAD == IRIVER_IFP7XX_PAD
#define JOY_UP           BUTTON_UP
#define JOY_DOWN         BUTTON_DOWN
#define CONSOLE_OPTION   BUTTON_EQ
#define CONSOLE_RESET    BUTTON_MODE
#define JOY_TRIGGER      BUTTON_SELECT
#define PLUGIN_QUIT      BUTTON_EQ

#elif CONFIG_KEYPAD == GIGABEAT_PAD
#define JOY_UP          BUTTON_UP
#define JOY_DOWN        BUTTON_DOWN
#define CONSOLE_RESET   BUTTON_VOL_UP
#define CONSOLE_OPTION  BUTTON_VOL_DOWN
#define JOY_TRIGGER     BUTTON_SELECT
#define PLUGIN_QUIT     BUTTON_MENU

#elif CONFIG_KEYPAD == SANSA_E200_PAD
#define JOY_UP          BUTTON_UP
#define JOY_DOWN        BUTTON_DOWN
#define JOY_TRIGGER     BUTTON_SELECT
#define CONSOLE_OPTION  BUTTON_REC
#define PLUGIN_QUIT     BUTTON_POWER
#define CONSOLE_RESET   BUTTON_NONE

#elif CONFIG_KEYPAD == SANSA_FUZE_PAD
#define JOY_UP          BUTTON_UP
#define JOY_DOWN        BUTTON_DOWN
#define JOY_TRIGGER     BUTTON_SELECT
#define CONSOLE_OPTION  BUTTON_HOME
#define PLUGIN_QUIT     BUTTON_POWER
#define CONSOLE_RESET   BUTTON_NONE

#elif CONFIG_KEYPAD == SANSA_C200_PAD
#define JOY_UP          BUTTON_UP
#define JOY_DOWN        BUTTON_DOWN
#define JOY_TRIGGER     BUTTON_SELECT
#define CONSOLE_OPTION  BUTTON_REC
#define PLUGIN_QUIT     BUTTON_POWER
#define CONSOLE_RESET   BUTTON_VOL_DOWN

#elif CONFIG_KEYPAD == SANSA_CLIP_PAD
#define JOY_UP          BUTTON_UP
#define JOY_DOWN        BUTTON_DOWN
#define JOY_TRIGGER     BUTTON_SELECT
#define CONSOLE_OPTION  BUTTON_HOME
#define CONSOLE_RESET   BUTTON_VOL_DOWN
#define PLUGIN_QUIT     BUTTON_POWER

/*    MARK */

#elif CONFIG_KEYPAD == IAUDIO_X5M5_PAD
#define JOY_UP          BUTTON_UP
#define JOY_DOWN        BUTTON_DOWN
#define CONSOLE_OPTION  BUTTON_REC
#define JOY_TRIGGER     BUTTON_SELECT
#define CONSOLE_RESET   BUTTON_PLAY
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == IRIVER_H10_PAD
#define JOY_UP          BUTTON_SCROLL_UP
#define JOY_DOWN        BUTTON_SCROLL_DOWN
#define JOY_TRIGGER     BUTTON_PLAY
#define CONSOLE_OPTION  BUTTON_FF
#define CONSOLE_RESET   BUTTON_REW
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == MROBE500_PAD
#define PLUGIN_QUIT    BUTTON_POWER
#define CONSOLE_RESET  BUTTON_NONE

#elif CONFIG_KEYPAD == COWON_D2_PAD
#define JOY_TRIGGER      BUTTON_PLUS
#define CONSOLE_OPTION   BUTTON_MINUS
#define PLUGIN_QUIT      BUTTON_MENU
#define CONSOLE_RESET   BUTTON_NONE

#elif CONFIG_KEYPAD == GIGABEAT_S_PAD
#define JOY_UP          BUTTON_UP
#define JOY_DOWN        BUTTON_DOWN
#define CONSOLE_OPTION  BUTTON_MENU
#define CONSOLE_RESET   BUTTON_BACK
#define JOY_TRIGGER     BUTTON_SELECT
#define PLUGIN_QUIT     BUTTON_POWER

#elif CONFIG_KEYPAD == CREATIVEZVM_PAD
#define JOY_UP          BUTTON_UP
#define JOY_DOWN        BUTTON_DOWN
#define CONSOLE_RESET   BUTTON_CUSTOM
#define CONSOLE_OPTION  BUTTON_PLAY
#define JOY_TRIGGER     BUTTON_SELECT
#define PLUGIN_QUIT     BUTTON_MENU

#elif CONFIG_KEYPAD == PHILIPS_HDD1630_PAD
#define JOY_UP          BUTTON_UP
#define JOY_DOWN        BUTTON_DOWN
#define CONSOLE_RESET   BUTTON_VOL_UP
#define CONSOLE_OPTION  BUTTON_VOL_DOWN
#define JOY_TRIGGER     BUTTON_SELECT
#define PLUGIN_QUIT     BUTTON_MENU

#elif CONFIG_KEYPAD == PHILIPS_HDD6330_PAD
#define JOY_UP         BUTTON_UP
#define JOY_DOWN       BUTTON_DOWN
#define CONSOLE_RESET  BUTTON_VOL_UP
#define CONSOLE_OPTION BUTTON_VOL_DOWN
#define JOY_TRIGGER    BUTTON_PLAY
#define PLUGIN_QUIT    BUTTON_MENU

#elif CONFIG_KEYPAD == PHILIPS_SA9200_PAD
#define JOY_UP         BUTTON_UP
#define JOY_DOWN       BUTTON_DOWN
#define JOY_TRIGGER    BUTTON_VOL_UP
#define CONSOLE_OPTION BUTTON_VOL_DOWN
#define PLUGIN_QUIT    BUTTON_MENU
#define CONSOLE_RESET  BUTTON_NONE

#elif CONFIG_KEYPAD == ONDAVX747_PAD
#define JOY_TRIGGER    BUTTON_VOL_UP
#define CONSOLE_OPTION BUTTON_VOL_DOWN
#define PLUGIN_QUIT    BUTTON_MENU
#define CONSOLE_RESET  BUTTON_NONE

#elif CONFIG_KEYPAD == ONDAVX777_PAD
#define PLUGIN_QUIT    BUTTON_POWER
#define CONSOLE_RESET  BUTTON_NONE

#elif CONFIG_KEYPAD == IRIVER_H10_PAD
#define JOY_UP          BUTTON_UP
#define JOY_DOWN        BUTTON_DOWN
#define JOY_TRIGGER     BUTTON_PLAY
#define CONSOLE_OPTION  BUTTON_FFWD
#define PLUGIN_QUIT     BUTTON_REW

#elif CONFIG_KEYPAD == SAMSUNG_YH_PAD
#define JOY_UP          BUTTON_UP
#define JOY_DOWN        BUTTON_DOWN
#define JOY_TRIGGER     BUTTON_PLAY
#define CONSOLE_OPTION  BUTTON_REW
#define CONSOLE_RESET   BUTTON_FFWD
#define PLUGIN_QUIT     BUTTON_REC

#elif CONFIG_KEYPAD == PBELL_VIBE500_PAD
#define JOY_UP          BUTTON_OK
#define JOY_DOWN        BUTTON_CANCEL
#define JOY_LEFT        BUTTON_PREV
#define JOY_RIGHT       BUTTON_NEXT
#define JOY_TRIGGER     BUTTON_POWER
#define CONSOLE_OPTION  BUTTON_REC
#define CONSOLE_RESET  BUTTON_PLAY
#define PLUGIN_QUIT     BUTTON_MENU

#elif CONFIG_KEYPAD == MPIO_HD300_PAD
#define JOY_UP         BUTTON_UP
#define JOY_DOWN       BUTTON_DOWN
#define JOY_LEFT       BUTTON_REW
#define JOY_RIGHT      BUTTON_FF
#define JOY_TRIGGER    BUTTON_PLAY
#define CONSOLE_OPTION BUTTON_REC
#define CONSOLE_RESET  BUTTON_ENTER
#define PLUGIN_QUIT    BUTTON_MENU

#elif CONFIG_KEYPAD == SANSA_FUZEPLUS_PAD
#define JOY_UP         BUTTON_UP
#define JOY_DOWN       BUTTON_DOWN
#define CONSOLE_RESET  BUTTON_VOL_UP
#define CONSOLE_OPTION BUTTON_VOL_DOWN
#define JOY_TRIGGER    BUTTON_SELECT
#define PLUGIN_QUIT    BUTTON_BACK

#elif CONFIG_KEYPAD == SANSA_CONNECT_PAD
#define JOY_UP         BUTTON_UP
#define JOY_DOWN       BUTTON_DOWN
#define CONSOLE_RESET  BUTTON_VOL_UP
#define CONSOLE_OPTION BUTTON_VOL_DOWN
#define PLUGIN_QUIT    BUTTON_NEXT
#define JOY_TRIGGER    BUTTON_SELECT

#elif CONFIG_KEYPAD == SAMSUNG_YPR0_PAD
#define JOY_UP         BUTTON_UP
#define JOY_DOWN       BUTTON_DOWN
#define JOY_TRIGGER    BUTTON_SELECT
#define CONSOLE_OPTION BUTTON_BACK
#define CONSOLE_RESET  BUTTON_USER
#define PLUGIN_QUIT    BUTTON_MENU

#elif CONFIG_KEYPAD == HM801_PAD
#define JOY_UP         BUTTON_UP
#define JOY_DOWN       BUTTON_DOWN
#define JOY_TRIGGER    BUTTON_PREV
#define CONSOLE_OPTION BUTTON_NEXT
#define CONSOLE_RESET  BUTTON_PLAY
#define JOY_TRIGGER    BUTTON_SELECT
#define PLUGIN_QUIT    BUTTON_POWER

#else
#error No Keymap Defined!
#endif

#ifdef HAVE_TOUCHSCREEN
#define JOY_UP          BUTTON_TOPMIDDLE
#define JOY_DOWN        BUTTON_BOTTOMMIDDLE
#define JOY_TRIGGER     BUTTON_TOPRIGHT
#define JOY_TRIGGER     BUTTON_CENTER
#if CONFIG_KEYPAD == MROBE500_PAD
#define JOY_TRIGGER     BUTTON_BOTTOMLEFT
#define CONSOLE_OPTION  BUTTON_BOTTOMRIGHT
#elif CONFIG_KEYPAD != COWON_D2_PAD
#define JOY_TRIGGER     BUTTON_BOTTOMLEFT
#define CONSOLE_OPTION  BUTTON_BOTTOMRIGHT
#define PLUGIN_QUIT     BUTTON_TOPLEFT
#endif
#define CONSOLE_RESET  BUTTON_NONE
#endif


/* was too lazy to change in all files :( */
#define memset rb->memset
#define memcpy rb->memcpy
#define strrchr rb->strrchr
#define strchr rb->strchr
#define strcpy rb->strcpy
#define strcmp rb->strcmp
#define strcat rb->strcat
#define printf (void)

#define SETTINGS_MIN_VERSION 1
#define SETTINGS_VERSION 1

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
/* #undef WORDS_BIGENDIAN */

/* Debugging Level */
#define Verbose 0

/* Xdebugger */
#undef XDEBUGGER

/* Define if you have the <unistd.h> header file.  */
#undef HAVE_UNISTD_H

#endif
