/* Automatically generated by configure - do not modify */
#ifndef _FFMPEG_CONFIG_H
#define _FFMPEG_CONFIG_H
#include "codecs.h"

#ifdef CPU_ARM
#define CONFIG_ALIGN 1
#endif

#ifdef ROCKBOX_BIG_ENDIAN
#define WORDS_BIGENDIAN
#endif

#endif
