/* Automatically generated by configure - do not modify */
#ifndef _CONFIG_H
#define _CONFIG_H

#define CONFIG_ALIGN 1

#define ARCH_X86 1
#undef HAVE_MMX
#define __CPU__ 586
#define HAVE_BUILTIN_VECTOR 1
#define HAVE_LOCALTIME_R 1
#define HAVE_LRINTF 1
#undef HAVE_VHOOK
#define HAVE_MALLOC_H 1
#define HAVE_MEMALIGN 1
#define SIMPLE_IDCT 1

#endif
