#!/bin/sh

######################################################################
#             __________               __   ___.
#   Open      \______   \ ____   ____ |  | _\_ |__   _______  ___
#   Source     |       _//  _ \_/ ___\|  |/ /| __ \ /  _ \  \/  /
#   Jukebox    |    |   (  <_> )  \___|    < | \_\ (  <_> > <  <
#   Firmware   |____|_  /\____/ \___  >__|_ \|___  /\____/__/\_ \
#                     \/            \/     \/    \/            \/
#
#   * Safe Mode for Samsung YP-Z5 / YP-Q2 platforms
#   * Copyright (C) 2017 Lorenzo Miori
######################################################################

# 0 = Z5 ; 1 = Q2
PLATFORM=0
#BUTTON_DEVICE="/dev/r0Btn"
#PMK=$(echo -e -n "\x01") # same for both devices
#STORAGES="/dev/stl3,/dev/stl2,/dev/mmcblk0"

MODE="normal"
RESOURCE_PATH="/Oasis/safemode"

if [ $# -eq 1 ]
then
    MODE=$1
fi

# rather simple but effective check
# different key codes to trigger safe mode
if [ -e "/z-proj/bin/z5decrypt" ]
then
    echo "YP-Z5 detected"
    PLATFORM=0
else
    PLATFORM=1
fi

# all useful tools are located here
cd /Oasis/usr/Oasis/bin

power_pressed()
{
    cat /proc/button | grep "Button # = 9"
    return $?
}

back_pressed()
{
    cat /proc/button | grep "Button # = 5"
    return $?
}

cable_disconnected()
{
    
    if [ $PLATFORM -eq 0 ]
    then
        # Error code 0 when disconnected
        ./usb-connected.sh
        return $?
#        if [ $? -eq 0 ]
#        then
#            return 1
#        else
#            return 0
#        fi
    else
        # TODO: Q2 platform
        return 0
    fi
}

enable_display()
{
    # set automatic refresh (enable DMA work)
    # nothing to do on YP-Z5
    echo "NOP" > /dev/null
}

display_image()
{
    echo "refresh 0" > /proc/lfbctrl
    cat $1 > "/dev/fb0"
    echo "refresh 1" > /proc/lfbctrl
}

if [ $MODE != "forced" ]
then
    back_pressed
    if [ $? -eq 1 ]
    then
      # do not enter safe mode and continue normal boot
        exit 0
    fi
fi

# Here we entered safe mode, so first clean the display
# and turn on backlight at minimum level
enable_display

# there are different ROMs around...
DefIMG="$RESOURCE_PATH/usbmode.raw"
RbtIMG="$RESOURCE_PATH/usbmode_post.raw"
PreIMG="$RESOURCE_PATH/usbmode_pre.raw"

NOUSB=true

if cable_disconnected
then

    display_image $PreIMG

    while $NOUSB
    do

        # User aborts safe mode before mounting anything, just exit
        # and continue normal boot
        if power_pressed
        then
            sleep 1
            if power_pressed
            then
                exit 1
            fi
        fi

        if cable_disconnected
        then
            echo "USB not connected - Waiting"
        else
            sleep 1
            if cable_disconnected
            then
                echo "USB first check OK - Waiting"
            else
                sleep 1
                if cable_disconnected
                then
                    echo "USB second check OK - Waiting"
                else
                    NOUSB=false
                    USB=true
                fi
            fi
        fi
    done
else
    while $NOUSB
    do
        if cable_disconnected
        then
            echo "USB not connected - Waiting"
        else
            sleep 1
            if cable_disconnected
            then
                echo "USB first check OK - Waiting"
            else
                NOUSB=false
                USB=true
            fi
        fi
    done
fi

display_image $DefIMG

echo "Enabling USB storage"
./usb-enable-hw.sh
./usb-enable.sh

SAFE=true
while $SAFE
do
    if power_pressed
    then
        sleep 1
        if power_pressed
        then
            SAFE=false
        fi
    fi
    # add also unmount of device
done

echo "Disabling USB storage"
./usb-disable.sh

display_image $RbtIMG

USB=true

while $USB
do
    if cable_disconnected
    then
        sleep 1
        if cable_disconnected
        then
            if cable_disconnected
            then
                sleep 1
                if cable_disconnected
                then
                    USB=false
                else
                    echo "USB connected - Waiting"
                    USB=true
                fi
            else
                echo "USB connected - Waiting"
                USB=true
            fi
        else
            echo "USB connected - Waiting"
            USB=true
        fi
    else
        echo "USB connected - Waiting"
        USB=true
    fi
done

#power key pressed for almost 2 sec and cable disconnected. Power off!
exit 1
