/* auto-generated by genhelp.sh */
/* DO NOT EDIT! */
const char help_text[] = 
"#Chapter 9: Netslide "
"\n"
"This game combines the grid generation of Net (see chapter 3) with "
"the movement of Sixteen (see chapter 6): you have a Net grid, but "
"instead of rotating tiles back into place you have to slide them "
"into place by moving a whole row at a time. "
"\n"
"As in Sixteen, control is with the mouse or cursor keys. See section "
"6.1. "
"\n"
"The available game parameters have similar meanings to those in Net "
"(see section 3.2) and Sixteen (see section 6.2). "
"\n"
"Netslide was contributed to this collection by Richard Boulton. "
"\n"
;
const char quick_help_text[] = "Slide a row at a time to reassemble the network.";
