/***************************************************************************
 *             __________               __   ___.
 *   Open      \______   \ ____   ____ |  | _\_ |__   _______  ___
 *   Source     |       _//  _ \_/ ___\|  |/ /| __ \ /  _ \  \/  /
 *   Jukebox    |    |   (  <_> )  \___|    < | \_\ (  <_> > <  <
 *   Firmware   |____|_  /\____/ \___  >__|_ \|___  /\____/__/\_ \
 *                     \/            \/     \/    \/            \/
 * This file was automatically generated by headergen, DO NOT EDIT it.
 *
 * Copyright (C) by Amaury Pouly
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 ****************************************************************************/
#ifndef __HEADERGEN_JZ4760B_H__
#define __HEADERGEN_JZ4760B_H__

#define CPM_ADDR                                0xb0000000
#define CPM_SYSCLK                              REG32(CPM_ADDR + 0x0)
#define CPM_SYSCLK_EXCLK_DIV                    (1 << 31)
#define CPM_SYSCLK_EXCLK_DIV_v(v)               ((CPM_SYSCLK_EXCLK_DIV_##v & 1) << 31)
#define CPM_SYSCLK_EXCLK_DIV_BY_1               0
#define CPM_SYSCLK_EXCLK_DIV_BY_2               1
#define CPM_SYSCLK_MEM_TYPE                     (1 << 30)
#define CPM_SYSCLK_MEM_TYPE_v(v)                ((CPM_SYSCLK_MEM_TYPE_##v & 1) << 30)
#define CPM_SYSCLK_MEM_TYPE_MDDR_SDRAM          0
#define CPM_SYSCLK_MEM_TYPE_DDR_DD2             1
#define CPM_SYSCLK_SCLK_DIV_bm                  (0xf << 24)
#define CPM_SYSCLK_SCLK_DIV(v)                  (((v) & 0xf) << 24)
#define CPM_SYSCLK_SCLK_DIV_v(v)                ((CPM_SYSCLK_SCLK_DIV_##v & 0xf) << 24)
#define CPM_SYSCLK_SCLK_DIV_get(v)              (((v) >> 24) & 0xf)
#define CPM_SYSCLK_SCLK_DIV_BY_1                0
#define CPM_SYSCLK_SCLK_DIV_BY_2                1
#define CPM_SYSCLK_SCLK_DIV_BY_3                2
#define CPM_SYSCLK_SCLK_DIV_BY_4                3
#define CPM_SYSCLK_SCLK_DIV_BY_6                4
#define CPM_SYSCLK_SCLK_DIV_BY_8                5
#define CPM_SYSCLK_EN_CHANGE                    (1 << 22)
#define CPM_SYSCLK_PLL_DIV                      (1 << 21)
#define CPM_SYSCLK_PLL_DIV_v(v)                 ((CPM_SYSCLK_PLL_DIV_##v & 1) << 21)
#define CPM_SYSCLK_PLL_DIV_BY_2                 0
#define CPM_SYSCLK_PLL_DIV_BY_1                 1
#define CPM_SYSCLK_H2CLK_DIV_bm                 (0xf << 16)
#define CPM_SYSCLK_H2CLK_DIV(v)                 (((v) & 0xf) << 16)
#define CPM_SYSCLK_H2CLK_DIV_v(v)               ((CPM_SYSCLK_H2CLK_DIV_##v & 0xf) << 16)
#define CPM_SYSCLK_H2CLK_DIV_get(v)             (((v) >> 16) & 0xf)
#define CPM_SYSCLK_H2CLK_DIV_BY_1               0
#define CPM_SYSCLK_H2CLK_DIV_BY_2               1
#define CPM_SYSCLK_H2CLK_DIV_BY_3               2
#define CPM_SYSCLK_H2CLK_DIV_BY_4               3
#define CPM_SYSCLK_H2CLK_DIV_BY_6               4
#define CPM_SYSCLK_H2CLK_DIV_BY_8               5
#define CPM_SYSCLK_MCLK_DIV_bm                  (0xf << 12)
#define CPM_SYSCLK_MCLK_DIV(v)                  (((v) & 0xf) << 12)
#define CPM_SYSCLK_MCLK_DIV_v(v)                ((CPM_SYSCLK_MCLK_DIV_##v & 0xf) << 12)
#define CPM_SYSCLK_MCLK_DIV_get(v)              (((v) >> 12) & 0xf)
#define CPM_SYSCLK_MCLK_DIV_BY_1                0
#define CPM_SYSCLK_MCLK_DIV_BY_2                1
#define CPM_SYSCLK_MCLK_DIV_BY_3                2
#define CPM_SYSCLK_MCLK_DIV_BY_4                3
#define CPM_SYSCLK_MCLK_DIV_BY_6                4
#define CPM_SYSCLK_MCLK_DIV_BY_8                5
#define CPM_SYSCLK_PCLK_DIV_bm                  (0xf << 8)
#define CPM_SYSCLK_PCLK_DIV(v)                  (((v) & 0xf) << 8)
#define CPM_SYSCLK_PCLK_DIV_v(v)                ((CPM_SYSCLK_PCLK_DIV_##v & 0xf) << 8)
#define CPM_SYSCLK_PCLK_DIV_get(v)              (((v) >> 8) & 0xf)
#define CPM_SYSCLK_PCLK_DIV_BY_1                0
#define CPM_SYSCLK_PCLK_DIV_BY_2                1
#define CPM_SYSCLK_PCLK_DIV_BY_3                2
#define CPM_SYSCLK_PCLK_DIV_BY_4                3
#define CPM_SYSCLK_PCLK_DIV_BY_6                4
#define CPM_SYSCLK_PCLK_DIV_BY_8                5
#define CPM_SYSCLK_HCLK_DIV_bm                  (0xf << 4)
#define CPM_SYSCLK_HCLK_DIV(v)                  (((v) & 0xf) << 4)
#define CPM_SYSCLK_HCLK_DIV_v(v)                ((CPM_SYSCLK_HCLK_DIV_##v & 0xf) << 4)
#define CPM_SYSCLK_HCLK_DIV_get(v)              (((v) >> 4) & 0xf)
#define CPM_SYSCLK_HCLK_DIV_BY_1                0
#define CPM_SYSCLK_HCLK_DIV_BY_2                1
#define CPM_SYSCLK_HCLK_DIV_BY_3                2
#define CPM_SYSCLK_HCLK_DIV_BY_4                3
#define CPM_SYSCLK_HCLK_DIV_BY_6                4
#define CPM_SYSCLK_HCLK_DIV_BY_8                5
#define CPM_SYSCLK_CCLK_DIV_bm                  (0xf << 0)
#define CPM_SYSCLK_CCLK_DIV(v)                  (((v) & 0xf) << 0)
#define CPM_SYSCLK_CCLK_DIV_v(v)                ((CPM_SYSCLK_CCLK_DIV_##v & 0xf) << 0)
#define CPM_SYSCLK_CCLK_DIV_get(v)              (((v) >> 0) & 0xf)
#define CPM_SYSCLK_CCLK_DIV_BY_1                0
#define CPM_SYSCLK_CCLK_DIV_BY_2                1
#define CPM_SYSCLK_CCLK_DIV_BY_3                2
#define CPM_SYSCLK_CCLK_DIV_BY_4                3
#define CPM_SYSCLK_CCLK_DIV_BY_6                4
#define CPM_SYSCLK_CCLK_DIV_BY_8                5
#define CPM_LOWPWR                              REG32(CPM_ADDR + 0x4)
#define CPM_LOWPWR_AHB1_PWD                     (1 << 30)
#define CPM_LOWPWR_VBAT_IR                      (1 << 29)
#define CPM_LOWPWR_GPS_PWD                      (1 << 28)
#define CPM_LOWPWR_AHB1S_PWD                    (1 << 26)
#define CPM_LOWPWR_GPSS_PWD                     (1 << 24)
#define CPM_LOWPWR_PWR_STABILITY_TIME_bm        (0xfff << 8)
#define CPM_LOWPWR_PWR_STABILITY_TIME(v)        (((v) & 0xfff) << 8)
#define CPM_LOWPWR_PWR_STABILITY_TIME_get(v)    (((v) >> 8) & 0xfff)
#define CPM_LOWPWR_DUTY_bm                      (0x1f << 3)
#define CPM_LOWPWR_DUTY(v)                      (((v) & 0x1f) << 3)
#define CPM_LOWPWR_DUTY_get(v)                  (((v) >> 3) & 0x1f)
#define CPM_LOWPWR_DOZE                         (1 << 2)
#define CPM_LOWPWR_SLEEP_MODE_bm                (3 << 0)
#define CPM_LOWPWR_SLEEP_MODE(v)                (((v) & 3) << 0)
#define CPM_LOWPWR_SLEEP_MODE_v(v)              ((CPM_LOWPWR_SLEEP_MODE_##v & 3) << 0)
#define CPM_LOWPWR_SLEEP_MODE_get(v)            (((v) >> 0) & 3)
#define CPM_LOWPWR_SLEEP_MODE_IDLE              0
#define CPM_LOWPWR_SLEEP_MODE_SLEEP             1
#define CPM_RESETSTS                            REG32(CPM_ADDR + 0x8)
#define CPM_RESETSTS_PWRUP_STS                  (1 << 2)
#define CPM_RESETSTS_WATCHDOG_STS               (1 << 1)
#define CPM_RESETSTS_PWRON_STS                  (1 << 0)
#define CPM_PLLCTRL0                            REG32(CPM_ADDR + 0x10)
#define CPM_PLLCTRL0_FEED_DIV_bm                (0x7f << 24)
#define CPM_PLLCTRL0_FEED_DIV(v)                (((v) & 0x7f) << 24)
#define CPM_PLLCTRL0_FEED_DIV_get(v)            (((v) >> 24) & 0x7f)
#define CPM_PLLCTRL0_IN_DIV_bm                  (0xf << 18)
#define CPM_PLLCTRL0_IN_DIV(v)                  (((v) & 0xf) << 18)
#define CPM_PLLCTRL0_IN_DIV_get(v)              (((v) >> 18) & 0xf)
#define CPM_PLLCTRL0_OUT_DIV_bm                 (3 << 16)
#define CPM_PLLCTRL0_OUT_DIV(v)                 (((v) & 3) << 16)
#define CPM_PLLCTRL0_OUT_DIV_v(v)               ((CPM_PLLCTRL0_OUT_DIV_##v & 3) << 16)
#define CPM_PLLCTRL0_OUT_DIV_get(v)             (((v) >> 16) & 3)
#define CPM_PLLCTRL0_OUT_DIV_BY_1               0
#define CPM_PLLCTRL0_OUT_DIV_BY_2               1
#define CPM_PLLCTRL0_OUT_DIV_BY_4               2
#define CPM_PLLCTRL0_OUT_DIV_BY_8               3
#define CPM_PLLCTRL0_LOCK                       (1 << 15)
#define CPM_PLLCTRL0_EN_LOCK                    (1 << 14)
#define CPM_PLLCTRL0_STABLE                     (1 << 10)
#define CPM_PLLCTRL0_BYPASS                     (1 << 9)
#define CPM_PLLCTRL0_ENABLE                     (1 << 8)
#define CPM_PLLCTRL0_STABILIZE_TIME_bm          (0xff << 0)
#define CPM_PLLCTRL0_STABILIZE_TIME(v)          (((v) & 0xff) << 0)
#define CPM_PLLCTRL0_STABILIZE_TIME_get(v)      (((v) >> 0) & 0xff)
#define CPM_PLLSWITCH                           REG32(CPM_ADDR + 0x14)
#define CPM_PLLSWITCH_OFF_STS                   (1 << 31)
#define CPM_PLLSWITCH_BYPASS_STS                (1 << 30)
#define CPM_PLLSWITCH_ON_STS                    (1 << 29)
#define CPM_PLLSWITCH_ENABLE_STS                (1 << 28)
#define CPM_PLLSWITCH_FREQ_STS                  (1 << 27)
#define CPM_PLLSWITCH_SRC_STS                   (1 << 26)
#define CPM_PLLSWITCH_SYS_CHANGE_MODE           (1 << 2)
#define CPM_PLLSWITCH_SYS_CHANGE_MODE_v(v)      ((CPM_PLLSWITCH_SYS_CHANGE_MODE_##v & 1) << 2)
#define CPM_PLLSWITCH_SYS_CHANGE_MODE_HW        0
#define CPM_PLLSWITCH_SYS_CHANGE_MODE_STOP      1
#define CPM_PLLSWITCH_SRC_SWITCH_MODE           (1 << 1)
#define CPM_PLLSWITCH_SRC_SWITCH_MODE_v(v)      ((CPM_PLLSWITCH_SRC_SWITCH_MODE_##v & 1) << 1)
#define CPM_PLLSWITCH_SRC_SWITCH_MODE_SLOW      0
#define CPM_PLLSWITCH_SRC_SWITCH_MODE_FAST      1
#define CPM_PLLSWITCH_FREQ_CHANGE_MODE          (1 << 0)
#define CPM_PLLSWITCH_FREQ_CHANGE_MODE_v(v)     ((CPM_PLLSWITCH_FREQ_CHANGE_MODE_##v & 1) << 0)
#define CPM_PLLSWITCH_FREQ_CHANGE_MODE_SLOW     0
#define CPM_PLLSWITCH_FREQ_CHANGE_MODE_FAST     1
#define CPM_CLKGATE0                            REG32(CPM_ADDR + 0x20)
#define CPM_CLKGATE0_EMC                        (1 << 31)
#define CPM_CLKGATE0_DDR                        (1 << 30)
#define CPM_CLKGATE0_IPU                        (1 << 29)
#define CPM_CLKGATE0_LCD                        (1 << 28)
#define CPM_CLKGATE0_TVE                        (1 << 27)
#define CPM_CLKGATE0_CIM                        (1 << 26)
#define CPM_CLKGATE0_MDMA                       (1 << 25)
#define CPM_CLKGATE0_UHC                        (1 << 24)
#define CPM_CLKGATE0_MAC                        (1 << 23)
#define CPM_CLKGATE0_GPS                        (1 << 22)
#define CPM_CLKGATE0_DMAC                       (1 << 21)
#define CPM_CLKGATE0_SSI2                       (1 << 20)
#define CPM_CLKGATE0_SSI1                       (1 << 19)
#define CPM_CLKGATE0_UART3                      (1 << 18)
#define CPM_CLKGATE0_UART2                      (1 << 17)
#define CPM_CLKGATE0_UART1                      (1 << 16)
#define CPM_CLKGATE0_UART0                      (1 << 15)
#define CPM_CLKGATE0_SADC                       (1 << 14)
#define CPM_CLKGATE0_KBC                        (1 << 13)
#define CPM_CLKGATE0_MSC2                       (1 << 12)
#define CPM_CLKGATE0_MSC1                       (1 << 11)
#define CPM_CLKGATE0_OWI                        (1 << 10)
#define CPM_CLKGATE0_TSSI                       (1 << 9)
#define CPM_CLKGATE0_AIC                        (1 << 8)
#define CPM_CLKGATE0_SCC                        (1 << 7)
#define CPM_CLKGATE0_I2C1                       (1 << 6)
#define CPM_CLKGATE0_I2C0                       (1 << 5)
#define CPM_CLKGATE0_SSI0                       (1 << 4)
#define CPM_CLKGATE0_MSC0                       (1 << 3)
#define CPM_CLKGATE0_OTG                        (1 << 2)
#define CPM_CLKGATE0_BCH                        (1 << 1)
#define CPM_CLKGATE0_NEMC                       (1 << 0)
#define CPM_OSCPWR                              REG32(CPM_ADDR + 0x24)
#define CPM_OSCPWR_STABILIZE_TIME_bm            (0xff << 8)
#define CPM_OSCPWR_STABILIZE_TIME(v)            (((v) & 0xff) << 8)
#define CPM_OSCPWR_STABILIZE_TIME_get(v)        (((v) >> 8) & 0xff)
#define CPM_OSCPWR_OTG_SUSPEND                  (1 << 7)
#define CPM_OSCPWR_GPS_ENABLE                   (1 << 6)
#define CPM_OSCPWR_UHC_SUSPEND                  (1 << 5)
#define CPM_OSCPWR_OSC_SLEEP                    (1 << 4)
#define CPM_OSCPWR_P0_SLEEP                     (1 << 3)
#define CPM_OSCPWR_SRC_SEL                      (1 << 2)
#define CPM_OSCPWR_SRC_SEL_v(v)                 ((CPM_OSCPWR_SRC_SEL_##v & 1) << 2)
#define CPM_OSCPWR_SRC_SEL_EXCLK_DIV_512        0
#define CPM_OSCPWR_SRC_SEL_RTCLK                1
#define CPM_CLKGATE1                            REG32(CPM_ADDR + 0x28)
#define CPM_CLKGATE1_AUX                        (1 << 11)
#define CPM_CLKGATE1_OSD                        (1 << 10)
#define CPM_CLKGATE1_GPU                        (1 << 9)
#define CPM_CLKGATE1_PCM                        (1 << 8)
#define CPM_CLKGATE1_AHB1                       (1 << 7)
#define CPM_CLKGATE1_CABAC                      (1 << 6)
#define CPM_CLKGATE1_SRAM                       (1 << 5)
#define CPM_CLKGATE1_DCT                        (1 << 4)
#define CPM_CLKGATE1_ME                         (1 << 3)
#define CPM_CLKGATE1_DBLK                       (1 << 2)
#define CPM_CLKGATE1_MC                         (1 << 1)
#define CPM_CLKGATE1_BDMA                       (1 << 0)
#define CPM_PLLCTRL1                            REG32(CPM_ADDR + 0x30)
#define CPM_PLLCTRL1_FEED_DIV_bm                (0x7f << 24)
#define CPM_PLLCTRL1_FEED_DIV(v)                (((v) & 0x7f) << 24)
#define CPM_PLLCTRL1_FEED_DIV_get(v)            (((v) >> 24) & 0x7f)
#define CPM_PLLCTRL1_IN_DIV_bm                  (0xf << 18)
#define CPM_PLLCTRL1_IN_DIV(v)                  (((v) & 0xf) << 18)
#define CPM_PLLCTRL1_IN_DIV_get(v)              (((v) >> 18) & 0xf)
#define CPM_PLLCTRL1_OUT_DIV_bm                 (3 << 16)
#define CPM_PLLCTRL1_OUT_DIV(v)                 (((v) & 3) << 16)
#define CPM_PLLCTRL1_OUT_DIV_v(v)               ((CPM_PLLCTRL1_OUT_DIV_##v & 3) << 16)
#define CPM_PLLCTRL1_OUT_DIV_get(v)             (((v) >> 16) & 3)
#define CPM_PLLCTRL1_OUT_DIV_BY_1               0
#define CPM_PLLCTRL1_OUT_DIV_BY_2               1
#define CPM_PLLCTRL1_OUT_DIV_BY_4               2
#define CPM_PLLCTRL1_OUT_DIV_BY_8               3
#define CPM_PLLCTRL1_SRC_SEL                    (1 << 15)
#define CPM_PLLCTRL1_SRC_SEL_v(v)               ((CPM_PLLCTRL1_SRC_SEL_##v & 1) << 15)
#define CPM_PLLCTRL1_SRC_SEL_EXCLK              0
#define CPM_PLLCTRL1_SRC_SEL_PLL0               1
#define CPM_PLLCTRL1_PLL0_DIV_bm                (0x3f << 9)
#define CPM_PLLCTRL1_PLL0_DIV(v)                (((v) & 0x3f) << 9)
#define CPM_PLLCTRL1_PLL0_DIV_get(v)            (((v) >> 9) & 0x3f)
#define CPM_PLLCTRL1_ENABLE                     (1 << 7)
#define CPM_PLLCTRL1_STABLE                     (1 << 6)
#define CPM_PLLCTRL1_LOCK                       (1 << 2)
#define CPM_PLLCTRL1_OFF                        (1 << 1)
#define CPM_PLLCTRL1_ON                         (1 << 0)
#define CPM_SCRATCH                             REG32(CPM_ADDR + 0x34)
#define CPM_SCRATCHPROT                         REG32(CPM_ADDR + 0x38)
#define CPM_USBCTRL                             REG32(CPM_ADDR + 0x3c)
#define CPM_USBCTRL_USB_MODE                    (1 << 31)
#define CPM_USBCTRL_AVLD_REG                    (1 << 30)
#define CPM_USBCTRL_IDPULLUP_bm                 (3 << 28)
#define CPM_USBCTRL_IDPULLUP(v)                 (((v) & 3) << 28)
#define CPM_USBCTRL_IDPULLUP_get(v)             (((v) >> 28) & 3)
#define CPM_USBCTRL_INCRM                       (1 << 27)
#define CPM_USBCTRL_CLK12_EN                    (1 << 26)
#define CPM_USBCTRL_COMMONONN                   (1 << 25)
#define CPM_USBCTRL_VBUSVLDEXT                  (1 << 24)
#define CPM_USBCTRL_VBUSVLDEXTSEL               (1 << 23)
#define CPM_USBCTRL_POR                         (1 << 22)
#define CPM_USBCTRL_SIDDQ                       (1 << 21)
#define CPM_USBCTRL_OTG_DISABLE                 (1 << 20)
#define CPM_USBCTRL_COMPDISTUNE_bm              (7 << 17)
#define CPM_USBCTRL_COMPDISTUNE(v)              (((v) & 7) << 17)
#define CPM_USBCTRL_COMPDISTUNE_get(v)          (((v) >> 17) & 7)
#define CPM_USBCTRL_OTGTUNE_bm                  (7 << 14)
#define CPM_USBCTRL_OTGTUNE(v)                  (((v) & 7) << 14)
#define CPM_USBCTRL_OTGTUNE_get(v)              (((v) >> 14) & 7)
#define CPM_USBCTRL_SQRXTUNE_bm                 (7 << 11)
#define CPM_USBCTRL_SQRXTUNE(v)                 (((v) & 7) << 11)
#define CPM_USBCTRL_SQRXTUNE_get(v)             (((v) >> 11) & 7)
#define CPM_USBCTRL_TXFSLSTUNE_bm               (0xf << 7)
#define CPM_USBCTRL_TXFSLSTUNE(v)               (((v) & 0xf) << 7)
#define CPM_USBCTRL_TXFSLSTUNE_get(v)           (((v) >> 7) & 0xf)
#define CPM_USBCTRL_TXPREEMPHTUNE               (1 << 6)
#define CPM_USBCTRL_TXRISETUNE_bm               (3 << 4)
#define CPM_USBCTRL_TXRISETUNE(v)               (((v) & 3) << 4)
#define CPM_USBCTRL_TXRISETUNE_get(v)           (((v) >> 4) & 3)
#define CPM_USBCTRL_TXVREFTUNE_bm               (0xf << 0)
#define CPM_USBCTRL_TXVREFTUNE(v)               (((v) & 0xf) << 0)
#define CPM_USBCTRL_TXVREFTUNE_get(v)           (((v) >> 0) & 0xf)
#define CPM_USBRESET                            REG32(CPM_ADDR + 0x40)
#define CPM_USBRESET_VBFIL_LD_EN                (1 << 25)
#define CPM_USBRESET_IDDIG_EN                   (1 << 24)
#define CPM_USBRESET_IDDIG_REG                  (1 << 23)
#define CPM_USBRESET_USBRDT_bm                  (0x7fffff << 0)
#define CPM_USBRESET_USBRDT(v)                  (((v) & 0x7fffff) << 0)
#define CPM_USBRESET_USBRDT_get(v)              (((v) >> 0) & 0x7fffff)
#define CPM_USBVBUS                             REG32(CPM_ADDR + 0x44)
#define CPM_USBCLK                              REG32(CPM_ADDR + 0x50)
#define CPM_USBCLK_SRC_SEL                      (1 << 31)
#define CPM_USBCLK_SRC_SEL_v(v)                 ((CPM_USBCLK_SRC_SEL_##v & 1) << 31)
#define CPM_USBCLK_SRC_SEL_EXCLK                0
#define CPM_USBCLK_SRC_SEL_PLL                  1
#define CPM_USBCLK_PLL_SEL                      (1 << 30)
#define CPM_USBCLK_PLL_SEL_v(v)                 ((CPM_USBCLK_PLL_SEL_##v & 1) << 30)
#define CPM_USBCLK_PLL_SEL_PLL0                 0
#define CPM_USBCLK_PLL_SEL_PLL1                 1
#define CPM_USBCLK_DIV_bm                       (0x3f << 0)
#define CPM_USBCLK_DIV(v)                       (((v) & 0x3f) << 0)
#define CPM_USBCLK_DIV_get(v)                   (((v) >> 0) & 0x3f)
#define CPM_I2SCLK                              REG32(CPM_ADDR + 0x60)
#define CPM_I2SCLK_SRC_SEL                      (1 << 31)
#define CPM_I2SCLK_SRC_SEL_v(v)                 ((CPM_I2SCLK_SRC_SEL_##v & 1) << 31)
#define CPM_I2SCLK_SRC_SEL_EXCLK                0
#define CPM_I2SCLK_SRC_SEL_PLL                  1
#define CPM_I2SCLK_PLL_SEL                      (1 << 30)
#define CPM_I2SCLK_PLL_SEL_v(v)                 ((CPM_I2SCLK_PLL_SEL_##v & 1) << 30)
#define CPM_I2SCLK_PLL_SEL_PLL0                 0
#define CPM_I2SCLK_PLL_SEL_PLL1                 1
#define CPM_I2SCLK_DIV_bm                       (0x1ff << 0)
#define CPM_I2SCLK_DIV(v)                       (((v) & 0x1ff) << 0)
#define CPM_I2SCLK_DIV_get(v)                   (((v) >> 0) & 0x1ff)
#define CPM_LCDCLK                              REG32(CPM_ADDR + 0x64)
#define CPM_LCDCLK_OUT_SEL                      (1 << 30)
#define CPM_LCDCLK_OUT_SEL_v(v)                 ((CPM_LCDCLK_OUT_SEL_##v & 1) << 30)
#define CPM_LCDCLK_OUT_SEL_LCD_PANEL            0
#define CPM_LCDCLK_OUT_SEL_TV_ENC               1
#define CPM_LCDCLK_PLL_SEL                      (1 << 29)
#define CPM_LCDCLK_PLL_SEL_v(v)                 ((CPM_LCDCLK_PLL_SEL_##v & 1) << 29)
#define CPM_LCDCLK_PLL_SEL_PLL0                 0
#define CPM_LCDCLK_PLL_SEL_PLL1                 1
#define CPM_LCDCLK_DIV_bm                       (0x7ff << 0)
#define CPM_LCDCLK_DIV(v)                       (((v) & 0x7ff) << 0)
#define CPM_LCDCLK_DIV_get(v)                   (((v) >> 0) & 0x7ff)
#define CPM_MSCCLK                              REG32(CPM_ADDR + 0x68)
#define CPM_MSCCLK_SRC_SEL                      (1 << 31)
#define CPM_MSCCLK_SRC_SEL_v(v)                 ((CPM_MSCCLK_SRC_SEL_##v & 1) << 31)
#define CPM_MSCCLK_SRC_SEL_EXCLK                0
#define CPM_MSCCLK_SRC_SEL_PLL                  1
#define CPM_MSCCLK_DIV_bm                       (0x3f << 0)
#define CPM_MSCCLK_DIV(v)                       (((v) & 0x3f) << 0)
#define CPM_MSCCLK_DIV_get(v)                   (((v) >> 0) & 0x3f)
#define CPM_UHCCLK                              REG32(CPM_ADDR + 0x6c)
#define CPM_UHCCLK_PLL_SEL                      (1 << 31)
#define CPM_UHCCLK_PLL_SEL_v(v)                 ((CPM_UHCCLK_PLL_SEL_##v & 1) << 31)
#define CPM_UHCCLK_PLL_SEL_PLL0                 0
#define CPM_UHCCLK_PLL_SEL_PLL1                 1
#define CPM_UHCCLK_DIV_bm                       (0xf << 0)
#define CPM_UHCCLK_DIV(v)                       (((v) & 0xf) << 0)
#define CPM_UHCCLK_DIV_get(v)                   (((v) >> 0) & 0xf)
#define CPM_SSICLK                              REG32(CPM_ADDR + 0x74)
#define CPM_SSICLK_SRC_SEL                      (1 << 31)
#define CPM_SSICLK_SRC_SEL_v(v)                 ((CPM_SSICLK_SRC_SEL_##v & 1) << 31)
#define CPM_SSICLK_SRC_SEL_EXCLK                0
#define CPM_SSICLK_SRC_SEL_PLL                  1
#define CPM_SSICLK_DIV_bm                       (0x3f << 0)
#define CPM_SSICLK_DIV(v)                       (((v) & 0x3f) << 0)
#define CPM_SSICLK_DIV_get(v)                   (((v) >> 0) & 0x3f)
#define CPM_CIM                                 REG32(CPM_ADDR + 0x7c)
#define CPM_CIM_DIV_bm                          (0xff << 0)
#define CPM_CIM_DIV(v)                          (((v) & 0xff) << 0)
#define CPM_CIM_DIV_get(v)                      (((v) >> 0) & 0xff)
#define CPM_GPS                                 REG32(CPM_ADDR + 0x80)
#define CPM_GPS_PLL_SEL                         (1 << 31)
#define CPM_GPS_PLL_SEL_v(v)                    ((CPM_GPS_PLL_SEL_##v & 1) << 31)
#define CPM_GPS_PLL_SEL_PLL0                    0
#define CPM_GPS_PLL_SEL_PLL1                    1
#define CPM_GPS_DIV_bm                          (0xf << 0)
#define CPM_GPS_DIV(v)                          (((v) & 0xf) << 0)
#define CPM_GPS_DIV_get(v)                      (((v) >> 0) & 0xf)
#define CPM_PCMCLK                              REG32(CPM_ADDR + 0x84)
#define CPM_PCMCLK_SRC_SEL                      (1 << 31)
#define CPM_PCMCLK_SRC_SEL_v(v)                 ((CPM_PCMCLK_SRC_SEL_##v & 1) << 31)
#define CPM_PCMCLK_SRC_SEL_EXCLK                0
#define CPM_PCMCLK_SRC_SEL_PLL                  1
#define CPM_PCMCLK_PLL_SEL                      (1 << 30)
#define CPM_PCMCLK_PLL_SEL_v(v)                 ((CPM_PCMCLK_PLL_SEL_##v & 1) << 30)
#define CPM_PCMCLK_PLL_SEL_PLL0                 0
#define CPM_PCMCLK_PLL_SEL_PLL1                 1
#define CPM_PCMCLK_DIV_bm                       (0x1ff << 0)
#define CPM_PCMCLK_DIV(v)                       (((v) & 0x1ff) << 0)
#define CPM_PCMCLK_DIV_get(v)                   (((v) >> 0) & 0x1ff)
#define CPM_GPUCLK                              REG32(CPM_ADDR + 0x88)
#define CPM_GPUCLK_PLL_SEL                      (1 << 31)
#define CPM_GPUCLK_PLL_SEL_v(v)                 ((CPM_GPUCLK_PLL_SEL_##v & 1) << 31)
#define CPM_GPUCLK_PLL_SEL_PLL0                 0
#define CPM_GPUCLK_PLL_SEL_PLL1                 1
#define CPM_GPUCLK_DIV_bm                       (7 << 0)
#define CPM_GPUCLK_DIV(v)                       (((v) & 7) << 0)
#define CPM_GPUCLK_DIV_get(v)                   (((v) >> 0) & 7)
#define CPM_PSWC0ST                             REG32(CPM_ADDR + 0x90)
#define CPM_PSWC1ST                             REG32(CPM_ADDR + 0x94)
#define CPM_PSWC2ST                             REG32(CPM_ADDR + 0x98)
#define CPM_PSWC3ST                             REG32(CPM_ADDR + 0x9c)

#define INTC_ADDR                               0xb0001000
#define INTC_STATUS(n)                          REG32(INTC_ADDR + 0x0 + (n) * 0x20)
#define INTC_MASK(n)                            REG32(INTC_ADDR + 0x4 + (n) * 0x20)
#define INTC_MASK_SET(n)                        REG32(INTC_ADDR + 0x4 + (n) * 0x20 + 0x4)
#define INTC_MASK_CLR(n)                        REG32(INTC_ADDR + 0x4 + (n) * 0x20 + 0x8)
#define INTC_PENDING(n)                         REG32(INTC_ADDR + 0x10 + (n) * 0x20)

#define OST_ADDR                                0xb0002000
#define OST_DATA                                REG32(OST_ADDR + 0xe0)
#define OST_COUNTL                              REG32(OST_ADDR + 0xe4)
#define OST_COUNTH                              REG32(OST_ADDR + 0xe8)
#define OST_CTRL                                REG16(OST_ADDR + 0xec)
#define OST_CTRL_IGNORE_COMPARE                 (1 << 15)
#define OST_CTRL_SHUTDOWN                       (1 << 9)
#define OST_CTRL_SHUTDOWN_v(v)                  ((OST_CTRL_SHUTDOWN_##v & 1) << 9)
#define OST_CTRL_SHUTDOWN_GRACEFUL              0
#define OST_CTRL_SHUTDOWN_ABRUPT                1
#define OST_CTRL_PRESCALE_bm                    (7 << 3)
#define OST_CTRL_PRESCALE(v)                    (((v) & 7) << 3)
#define OST_CTRL_PRESCALE_v(v)                  ((OST_CTRL_PRESCALE_##v & 7) << 3)
#define OST_CTRL_PRESCALE_get(v)                (((v) >> 3) & 7)
#define OST_CTRL_PRESCALE_1                     0
#define OST_CTRL_PRESCALE_4                     1
#define OST_CTRL_PRESCALE_16                    2
#define OST_CTRL_PRESCALE_64                    3
#define OST_CTRL_PRESCALE_256                   4
#define OST_CTRL_PRESCALE_1024                  5
#define OST_CTRL_EXT_EN                         (1 << 2)
#define OST_CTRL_RTC_EN                         (1 << 1)
#define OST_CTRL_PCK_EN                         (1 << 0)
#define OST_COUNTH_BUF                          REG32(OST_ADDR + 0xfc)

#define TCU_ADDR                                0xb0002000
#define TCU_ENABLE                              REG16(TCU_ADDR + 0x10)
#define TCU_ENABLE_SET                          REG16(TCU_ADDR + 0x10 + 0x4)
#define TCU_ENABLE_CLR                          REG16(TCU_ADDR + 0x10 + 0x8)
#define TCU_ENABLE_OST                          (1 << 15)
#define TCU_ENABLE_TIMER_bm                     (0xff << 0)
#define TCU_ENABLE_TIMER(v)                     (((v) & 0xff) << 0)
#define TCU_ENABLE_TIMER_get(v)                 (((v) >> 0) & 0xff)
#define TCU_STOP                                REG32(TCU_ADDR + 0x1c)
#define TCU_STOP_SET                            REG32(TCU_ADDR + 0x1c + 0x10)
#define TCU_STOP_CLR                            REG32(TCU_ADDR + 0x1c + 0x20)
#define TCU_STOP_WDT                            (1 << 16)
#define TCU_STOP_OST                            (1 << 15)
#define TCU_STOP_TIMER_bm                       (0xff << 0)
#define TCU_STOP_TIMER(v)                       (((v) & 0xff) << 0)
#define TCU_STOP_TIMER_get(v)                   (((v) >> 0) & 0xff)
#define TCU_FLAG                                REG32(TCU_ADDR + 0x20)
#define TCU_FLAG_SET                            REG32(TCU_ADDR + 0x20 + 0x4)
#define TCU_FLAG_CLR                            REG32(TCU_ADDR + 0x20 + 0x8)
#define TCU_FLAG_HALF_bm                        (0xff << 16)
#define TCU_FLAG_HALF(v)                        (((v) & 0xff) << 16)
#define TCU_FLAG_HALF_get(v)                    (((v) >> 16) & 0xff)
#define TCU_FLAG_OST                            (1 << 15)
#define TCU_FLAG_FULL_bm                        (0xff << 0)
#define TCU_FLAG_FULL(v)                        (((v) & 0xff) << 0)
#define TCU_FLAG_FULL_get(v)                    (((v) >> 0) & 0xff)
#define TCU_TMR                                 REG32(TCU_ADDR + 0x30)
#define TCU_TMR_SET                             REG32(TCU_ADDR + 0x30 + 0x4)
#define TCU_TMR_CLR                             REG32(TCU_ADDR + 0x30 + 0x8)
#define TCU_TMR_HALF_bm                         (0xff << 16)
#define TCU_TMR_HALF(v)                         (((v) & 0xff) << 16)
#define TCU_TMR_HALF_get(v)                     (((v) >> 16) & 0xff)
#define TCU_TMR_OST                             (1 << 15)
#define TCU_TMR_FULL_bm                         (0xff << 0)
#define TCU_TMR_FULL(v)                         (((v) & 0xff) << 0)
#define TCU_TMR_FULL_get(v)                     (((v) >> 0) & 0xff)
#define TCU_DATA_FULL(n)                        REG16(TCU_ADDR + 0x40 + (n) * 0x10)
#define TCU_DATA_FULL_COUNT_bm                  (0xffff << 0)
#define TCU_DATA_FULL_COUNT(v)                  (((v) & 0xffff) << 0)
#define TCU_DATA_FULL_COUNT_get(v)              (((v) >> 0) & 0xffff)
#define TCU_DATA_HALF(n)                        REG16(TCU_ADDR + 0x44 + (n) * 0x10)
#define TCU_DATA_HALF_COUNT_bm                  (0xffff << 0)
#define TCU_DATA_HALF_COUNT(v)                  (((v) & 0xffff) << 0)
#define TCU_DATA_HALF_COUNT_get(v)              (((v) >> 0) & 0xffff)
#define TCU_COUNT(n)                            REG16(TCU_ADDR + 0x48 + (n) * 0x10)
#define TCU_COUNT_COUNT_bm                      (0xffff << 0)
#define TCU_COUNT_COUNT(v)                      (((v) & 0xffff) << 0)
#define TCU_COUNT_COUNT_get(v)                  (((v) >> 0) & 0xffff)
#define TCU_CTRL(n)                             REG16(TCU_ADDR + 0x4c + (n) * 0x10)
#define TCU_CTRL_CLEAR_TO_ZERO                  (1 << 10)
#define TCU_CTRL_SHUTDOWN                       (1 << 9)
#define TCU_CTRL_SHUTDOWN_v(v)                  ((TCU_CTRL_SHUTDOWN_##v & 1) << 9)
#define TCU_CTRL_SHUTDOWN_GRACEFUL              0
#define TCU_CTRL_SHUTDOWN_ABRUPT                1
#define TCU_CTRL_PMW_INIT_LVL                   (1 << 8)
#define TCU_CTRL_PWM_EN                         (1 << 7)
#define TCU_CTRL_PWM_IN_EN                      (1 << 6)
#define TCU_CTRL_PRESCALE_bm                    (7 << 3)
#define TCU_CTRL_PRESCALE(v)                    (((v) & 7) << 3)
#define TCU_CTRL_PRESCALE_v(v)                  ((TCU_CTRL_PRESCALE_##v & 7) << 3)
#define TCU_CTRL_PRESCALE_get(v)                (((v) >> 3) & 7)
#define TCU_CTRL_PRESCALE_1                     0
#define TCU_CTRL_PRESCALE_4                     1
#define TCU_CTRL_PRESCALE_16                    2
#define TCU_CTRL_PRESCALE_64                    3
#define TCU_CTRL_PRESCALE_256                   4
#define TCU_CTRL_PRESCALE_1024                  5
#define TCU_CTRL_EXT_EN                         (1 << 2)
#define TCU_CTRL_RTC_EN                         (1 << 1)
#define TCU_CTRL_PCK_EN                         (1 << 0)
#define TCU_TSTR                                REG32(TCU_ADDR + 0xf0)
#define TCU_TSTR_SET                            REG32(TCU_ADDR + 0xf0 + 0x4)
#define TCU_TSTR_CLR                            REG32(TCU_ADDR + 0xf0 + 0x8)
#define TCU_TSTR_REAL2                          (1 << 18)
#define TCU_TSTR_REAL1                          (1 << 17)
#define TCU_TSTR_BUSY2                          (1 << 2)
#define TCU_TSTR_BUSY1                          (1 << 1)

#define GPIO_ADDR                               0xb0010000
#define GPIO_IN(n)                              REG32(GPIO_ADDR + 0x0 + (n) * 0x100)
#define GPIO_OUT(n)                             REG32(GPIO_ADDR + 0x10 + (n) * 0x100)
#define GPIO_OUT_SET(n)                         REG32(GPIO_ADDR + 0x10 + (n) * 0x100 + 0x4)
#define GPIO_OUT_CLR(n)                         REG32(GPIO_ADDR + 0x10 + (n) * 0x100 + 0x8)
#define GPIO_FLGC(n)                            REG32(GPIO_ADDR + 0x14 + (n) * 0x100)
#define GPIO_MASK(n)                            REG32(GPIO_ADDR + 0x20 + (n) * 0x100)
#define GPIO_MASK_SET(n)                        REG32(GPIO_ADDR + 0x20 + (n) * 0x100 + 0x4)
#define GPIO_MASK_CLR(n)                        REG32(GPIO_ADDR + 0x20 + (n) * 0x100 + 0x8)
#define GPIO_PULL(n)                            REG32(GPIO_ADDR + 0x30 + (n) * 0x100)
#define GPIO_PULL_SET(n)                        REG32(GPIO_ADDR + 0x30 + (n) * 0x100 + 0x4)
#define GPIO_PULL_CLR(n)                        REG32(GPIO_ADDR + 0x30 + (n) * 0x100 + 0x8)
#define GPIO_FUNCTION(n)                        REG32(GPIO_ADDR + 0x40 + (n) * 0x100)
#define GPIO_FUNCTION_SET(n)                    REG32(GPIO_ADDR + 0x40 + (n) * 0x100 + 0x4)
#define GPIO_FUNCTION_CLR(n)                    REG32(GPIO_ADDR + 0x40 + (n) * 0x100 + 0x8)
#define GPIO_SELECT(n)                          REG32(GPIO_ADDR + 0x50 + (n) * 0x100)
#define GPIO_SELECT_SET(n)                      REG32(GPIO_ADDR + 0x50 + (n) * 0x100 + 0x4)
#define GPIO_SELECT_CLR(n)                      REG32(GPIO_ADDR + 0x50 + (n) * 0x100 + 0x8)
#define GPIO_DIR(n)                             REG32(GPIO_ADDR + 0x60 + (n) * 0x100)
#define GPIO_DIR_SET(n)                         REG32(GPIO_ADDR + 0x60 + (n) * 0x100 + 0x4)
#define GPIO_DIR_CLR(n)                         REG32(GPIO_ADDR + 0x60 + (n) * 0x100 + 0x8)
#define GPIO_TRIGGER(n)                         REG32(GPIO_ADDR + 0x70 + (n) * 0x100)
#define GPIO_TRIGGER_SET(n)                     REG32(GPIO_ADDR + 0x70 + (n) * 0x100 + 0x4)
#define GPIO_TRIGGER_CLR(n)                     REG32(GPIO_ADDR + 0x70 + (n) * 0x100 + 0x8)
#define GPIO_FLG(n)                             REG32(GPIO_ADDR + 0x80 + (n) * 0x100)
#define GPIO_DRIVE0(n)                          REG32(GPIO_ADDR + 0xc0 + (n) * 0x100)
#define GPIO_DRIVE0_SET(n)                      REG32(GPIO_ADDR + 0xc0 + (n) * 0x100 + 0x4)
#define GPIO_DRIVE0_CLR(n)                      REG32(GPIO_ADDR + 0xc0 + (n) * 0x100 + 0x8)
#define GPIO_DRIVE1(n)                          REG32(GPIO_ADDR + 0xd0 + (n) * 0x100)
#define GPIO_DRIVE1_SET(n)                      REG32(GPIO_ADDR + 0xd0 + (n) * 0x100 + 0x4)
#define GPIO_DRIVE1_CLR(n)                      REG32(GPIO_ADDR + 0xd0 + (n) * 0x100 + 0x8)
#define GPIO_DRIVE2(n)                          REG32(GPIO_ADDR + 0xe0 + (n) * 0x100)
#define GPIO_DRIVE2_SET(n)                      REG32(GPIO_ADDR + 0xe0 + (n) * 0x100 + 0x4)
#define GPIO_DRIVE2_CLR(n)                      REG32(GPIO_ADDR + 0xe0 + (n) * 0x100 + 0x8)
#define GPIO_SLEW(n)                            REG32(GPIO_ADDR + 0xf0 + (n) * 0x100)
#define GPIO_SLEW_SET(n)                        REG32(GPIO_ADDR + 0xf0 + (n) * 0x100 + 0x4)
#define GPIO_SLEW_CLR(n)                        REG32(GPIO_ADDR + 0xf0 + (n) * 0x100 + 0x8)

#define LCD_ADDR                                0xb3050000
#define LCD_CFG                                 REG32(LCD_ADDR + 0x0)
#define LCD_CFG_LCDPIN                          (1 << 31)
#define LCD_CFG_LCDPIN_v(v)                     ((LCD_CFG_LCDPIN_##v & 1) << 31)
#define LCD_CFG_LCDPIN_LCD                      0
#define LCD_CFG_LCDPIN_SLCD                     1
#define LCD_CFG_TVEPEH                          (1 << 30)
#define LCD_CFG_FUHOLD                          (1 << 29)
#define LCD_CFG_NEWDES                          (1 << 28)
#define LCD_CFG_PALBP                           (1 << 27)
#define LCD_CFG_TVEN                            (1 << 26)
#define LCD_CFG_RECOVER                         (1 << 25)
#define LCD_CFG_DITHER                          (1 << 24)
#define LCD_CFG_PSM                             (1 << 23)
#define LCD_CFG_CLSM                            (1 << 22)
#define LCD_CFG_SPLM                            (1 << 21)
#define LCD_CFG_REVM                            (1 << 20)
#define LCD_CFG_HSYNM                           (1 << 19)
#define LCD_CFG_PCLKM                           (1 << 18)
#define LCD_CFG_INVDAT                          (1 << 17)
#define LCD_CFG_SYNDIR_IN                       (1 << 16)
#define LCD_CFG_PSP                             (1 << 15)
#define LCD_CFG_CLSP                            (1 << 14)
#define LCD_CFG_SPLP                            (1 << 13)
#define LCD_CFG_REVP                            (1 << 12)
#define LCD_CFG_HSP                             (1 << 11)
#define LCD_CFG_PCP                             (1 << 10)
#define LCD_CFG_DEP                             (1 << 9)
#define LCD_CFG_VSP                             (1 << 8)
#define LCD_CFG_MODE_TFT_18BIT                  (1 << 7)
#define LCD_CFG_MODE_TFT_24BIT                  (1 << 6)
#define LCD_CFG_PDW_bm                          (3 << 4)
#define LCD_CFG_PDW(v)                          (((v) & 3) << 4)
#define LCD_CFG_PDW_v(v)                        ((LCD_CFG_PDW_##v & 3) << 4)
#define LCD_CFG_PDW_get(v)                      (((v) >> 4) & 3)
#define LCD_CFG_PDW_1                           0
#define LCD_CFG_PDW_2                           1
#define LCD_CFG_PDW_4                           2
#define LCD_CFG_PDW_8                           3
#define LCD_CFG_MODE_bm                         (0xf << 0)
#define LCD_CFG_MODE(v)                         (((v) & 0xf) << 0)
#define LCD_CFG_MODE_v(v)                       ((LCD_CFG_MODE_##v & 0xf) << 0)
#define LCD_CFG_MODE_get(v)                     (((v) >> 0) & 0xf)
#define LCD_CFG_MODE_GENERIC_TFT                0
#define LCD_CFG_MODE_SPECIAL_TFT_1              1
#define LCD_CFG_MODE_SPECIAL_TFT_2              2
#define LCD_CFG_MODE_SPECIAL_TFT_3              3
#define LCD_CFG_MODE_NONINTER_CCIR656           4
#define LCD_CFG_MODE_INTER_CCIR656              6
#define LCD_CFG_MODE_SINGLE_CSTN                8
#define LCD_CFG_MODE_SINGLE_MSTN                9
#define LCD_CFG_MODE_DUAL_CSTN                  0xa
#define LCD_CFG_MODE_DUAL_MSTN                  0xb
#define LCD_CFG_MODE_SERIAL_TFT                 0xc
#define LCD_CFG_MODE_LCM                        0xd
#define LCD_VSYNC                               REG32(LCD_ADDR + 0x4)
#define LCD_VSYNC_VPS_bm                        (0xffff << 16)
#define LCD_VSYNC_VPS(v)                        (((v) & 0xffff) << 16)
#define LCD_VSYNC_VPS_get(v)                    (((v) >> 16) & 0xffff)
#define LCD_VSYNC_VPE_bm                        (0xffff << 0)
#define LCD_VSYNC_VPE(v)                        (((v) & 0xffff) << 0)
#define LCD_VSYNC_VPE_get(v)                    (((v) >> 0) & 0xffff)
#define LCD_HSYNC                               REG32(LCD_ADDR + 0x8)
#define LCD_HSYNC_HPS_bm                        (0xffff << 16)
#define LCD_HSYNC_HPS(v)                        (((v) & 0xffff) << 16)
#define LCD_HSYNC_HPS_get(v)                    (((v) >> 16) & 0xffff)
#define LCD_HSYNC_HPE_bm                        (0xffff << 0)
#define LCD_HSYNC_HPE(v)                        (((v) & 0xffff) << 0)
#define LCD_HSYNC_HPE_get(v)                    (((v) >> 0) & 0xffff)
#define LCD_VAT                                 REG32(LCD_ADDR + 0xc)
#define LCD_VAT_HT_bm                           (0xffff << 16)
#define LCD_VAT_HT(v)                           (((v) & 0xffff) << 16)
#define LCD_VAT_HT_get(v)                       (((v) >> 16) & 0xffff)
#define LCD_VAT_VT_bm                           (0xffff << 0)
#define LCD_VAT_VT(v)                           (((v) & 0xffff) << 0)
#define LCD_VAT_VT_get(v)                       (((v) >> 0) & 0xffff)
#define LCD_DAH                                 REG32(LCD_ADDR + 0x10)
#define LCD_DAH_HDS_bm                          (0xffff << 16)
#define LCD_DAH_HDS(v)                          (((v) & 0xffff) << 16)
#define LCD_DAH_HDS_get(v)                      (((v) >> 16) & 0xffff)
#define LCD_DAH_HDE_bm                          (0xffff << 0)
#define LCD_DAH_HDE(v)                          (((v) & 0xffff) << 0)
#define LCD_DAH_HDE_get(v)                      (((v) >> 0) & 0xffff)
#define LCD_DAV                                 REG32(LCD_ADDR + 0x14)
#define LCD_DAV_VDS_bm                          (0xffff << 16)
#define LCD_DAV_VDS(v)                          (((v) & 0xffff) << 16)
#define LCD_DAV_VDS_get(v)                      (((v) >> 16) & 0xffff)
#define LCD_DAV_VDE_bm                          (0xffff << 0)
#define LCD_DAV_VDE(v)                          (((v) & 0xffff) << 0)
#define LCD_DAV_VDE_get(v)                      (((v) >> 0) & 0xffff)
#define LCD_PS                                  REG32(LCD_ADDR + 0x18)
#define LCD_PS_PSS_bm                           (0xffff << 16)
#define LCD_PS_PSS(v)                           (((v) & 0xffff) << 16)
#define LCD_PS_PSS_get(v)                       (((v) >> 16) & 0xffff)
#define LCD_PS_PSE_bm                           (0xffff << 0)
#define LCD_PS_PSE(v)                           (((v) & 0xffff) << 0)
#define LCD_PS_PSE_get(v)                       (((v) >> 0) & 0xffff)
#define LCD_CLS                                 REG32(LCD_ADDR + 0x1c)
#define LCD_CLS_CLSS_bm                         (0xffff << 16)
#define LCD_CLS_CLSS(v)                         (((v) & 0xffff) << 16)
#define LCD_CLS_CLSS_get(v)                     (((v) >> 16) & 0xffff)
#define LCD_CLS_CLSE_bm                         (0xffff << 0)
#define LCD_CLS_CLSE(v)                         (((v) & 0xffff) << 0)
#define LCD_CLS_CLSE_get(v)                     (((v) >> 0) & 0xffff)
#define LCD_SPL                                 REG32(LCD_ADDR + 0x20)
#define LCD_SPL_SPLS_bm                         (0xffff << 16)
#define LCD_SPL_SPLS(v)                         (((v) & 0xffff) << 16)
#define LCD_SPL_SPLS_get(v)                     (((v) >> 16) & 0xffff)
#define LCD_SPL_SPLE_bm                         (0xffff << 0)
#define LCD_SPL_SPLE(v)                         (((v) & 0xffff) << 0)
#define LCD_SPL_SPLE_get(v)                     (((v) >> 0) & 0xffff)
#define LCD_REV                                 REG32(LCD_ADDR + 0x24)
#define LCD_REV_REVS_bm                         (0xffff << 16)
#define LCD_REV_REVS(v)                         (((v) & 0xffff) << 16)
#define LCD_REV_REVS_get(v)                     (((v) >> 16) & 0xffff)
#define LCD_CTRL                                REG32(LCD_ADDR + 0x30)
#define LCD_CTRL_PINMD                          (1 << 31)
#define LCD_CTRL_BST_bm                         (7 << 28)
#define LCD_CTRL_BST(v)                         (((v) & 7) << 28)
#define LCD_CTRL_BST_v(v)                       ((LCD_CTRL_BST_##v & 7) << 28)
#define LCD_CTRL_BST_get(v)                     (((v) >> 28) & 7)
#define LCD_CTRL_BST_4                          0
#define LCD_CTRL_BST_8                          1
#define LCD_CTRL_BST_16                         2
#define LCD_CTRL_BST_32                         3
#define LCD_CTRL_BST_64                         4
#define LCD_CTRL_BST_16_CTN                     5
#define LCD_CTRL_BST_C16                        5
#define LCD_CTRL_RGB555                         (1 << 27)
#define LCD_CTRL_OFUP                           (1 << 26)
#define LCD_CTRL_FRC_bm                         (3 << 24)
#define LCD_CTRL_FRC(v)                         (((v) & 3) << 24)
#define LCD_CTRL_FRC_v(v)                       ((LCD_CTRL_FRC_##v & 3) << 24)
#define LCD_CTRL_FRC_get(v)                     (((v) >> 24) & 3)
#define LCD_CTRL_FRC_16                         0
#define LCD_CTRL_FRC_4                          1
#define LCD_CTRL_FRC_2                          2
#define LCD_CTRL_PDD_bm                         (0xff << 16)
#define LCD_CTRL_PDD(v)                         (((v) & 0xff) << 16)
#define LCD_CTRL_PDD_get(v)                     (((v) >> 16) & 0xff)
#define LCD_CTRL_EOFM                           (1 << 13)
#define LCD_CTRL_SOFM                           (1 << 12)
#define LCD_CTRL_OFUM                           (1 << 11)
#define LCD_CTRL_IFUM0                          (1 << 10)
#define LCD_CTRL_IFUM1                          (1 << 9)
#define LCD_CTRL_LDDM                           (1 << 8)
#define LCD_CTRL_QDM                            (1 << 7)
#define LCD_CTRL_BEDN                           (1 << 6)
#define LCD_CTRL_PEDN                           (1 << 5)
#define LCD_CTRL_DIS                            (1 << 4)
#define LCD_CTRL_ENA                            (1 << 3)
#define LCD_CTRL_BPP_bm                         (7 << 0)
#define LCD_CTRL_BPP(v)                         (((v) & 7) << 0)
#define LCD_CTRL_BPP_v(v)                       ((LCD_CTRL_BPP_##v & 7) << 0)
#define LCD_CTRL_BPP_get(v)                     (((v) >> 0) & 7)
#define LCD_CTRL_BPP_1                          0
#define LCD_CTRL_BPP_2                          1
#define LCD_CTRL_BPP_4                          2
#define LCD_CTRL_BPP_8                          3
#define LCD_CTRL_BPP_16                         4
#define LCD_CTRL_BPP_18_24                      5
#define LCD_CTRL_BPP_CMPS_24                    6
#define LCD_CTRL_BPP_30                         7
#define LCD_STATE                               REG32(LCD_ADDR + 0x34)
#define LCD_STATE_FEND                          (1 << 22)
#define LCD_STATE_PWRUP                         (1 << 20)
#define LCD_STATE_PWRDN                         (1 << 19)
#define LCD_STATE_QD                            (1 << 7)
#define LCD_STATE_EOF                           (1 << 5)
#define LCD_STATE_SOF                           (1 << 4)
#define LCD_STATE_OFU                           (1 << 3)
#define LCD_STATE_IFU0                          (1 << 2)
#define LCD_STATE_IFU1                          (1 << 1)
#define LCD_STATE_LDD                           (1 << 0)
#define LCD_IID                                 REG32(LCD_ADDR + 0x38)
#define LCD_DA(n)                               REG32(LCD_ADDR + 0x40 + (n) * 0x10)
#define LCD_SA(n)                               REG32(LCD_ADDR + 0x44 + (n) * 0x10)
#define LCD_FID(n)                              REG32(LCD_ADDR + 0x48 + (n) * 0x10)
#define LCD_CMD(n)                              REG32(LCD_ADDR + 0x4c + (n) * 0x10)
#define LCD_CMD_SOFINT                          (1 << 31)
#define LCD_CMD_EOFINT                          (1 << 30)
#define LCD_CMD_CMD                             (1 << 29)
#define LCD_CMD_PAL                             (1 << 28)
#define LCD_CMD_LEN_bm                          (0xffffff << 0)
#define LCD_CMD_LEN(v)                          (((v) & 0xffffff) << 0)
#define LCD_CMD_LEN_get(v)                      (((v) >> 0) & 0xffffff)
#define LCD_OFFS(n)                             REG32(LCD_ADDR + 0x60 + (n) * 0x10)
#define LCD_PW(n)                               REG32(LCD_ADDR + 0x64 + (n) * 0x10)
#define LCD_CNUM(n)                             REG32(LCD_ADDR + 0x68 + (n) * 0x10)
#define LCD_DESSIZE(n)                          REG32(LCD_ADDR + 0x6c + (n) * 0x10)
#define LCD_DESSIZE_HEIGHT_bm                   (0xffff << 16)
#define LCD_DESSIZE_HEIGHT(v)                   (((v) & 0xffff) << 16)
#define LCD_DESSIZE_HEIGHT_get(v)               (((v) >> 16) & 0xffff)
#define LCD_DESSIZE_WIDTH_bm                    (0xffff << 0)
#define LCD_DESSIZE_WIDTH(v)                    (((v) & 0xffff) << 0)
#define LCD_DESSIZE_WIDTH_get(v)                (((v) >> 0) & 0xffff)
#define LCD_RGBC                                REG16(LCD_ADDR + 0x90)
#define LCD_RGBC_RGBDM                          (1 << 15)
#define LCD_RGBC_DMM                            (1 << 14)
#define LCD_RGBC_YCC                            (1 << 8)
#define LCD_RGBC_ODDRGB_bm                      (7 << 4)
#define LCD_RGBC_ODDRGB(v)                      (((v) & 7) << 4)
#define LCD_RGBC_ODDRGB_get(v)                  (((v) >> 4) & 7)
#define LCD_RGBC_EVENRGB_bm                     (7 << 0)
#define LCD_RGBC_EVENRGB(v)                     (((v) & 7) << 0)
#define LCD_RGBC_EVENRGB_get(v)                 (((v) >> 0) & 7)
#define LCD_OSDC                                REG16(LCD_ADDR + 0x100)
#define LCD_OSDC_SOFM1                          (1 << 15)
#define LCD_OSDC_EOFM1                          (1 << 14)
#define LCD_OSDC_SOFM0                          (1 << 11)
#define LCD_OSDC_EOFM0                          (1 << 10)
#define LCD_OSDC_ENDM                           (1 << 9)
#define LCD_OSDC_F1EN                           (1 << 4)
#define LCD_OSDC_F0EN                           (1 << 3)
#define LCD_OSDC_ALPHAEN                        (1 << 2)
#define LCD_OSDC_ALPHAMD                        (1 << 1)
#define LCD_OSDC_OSDEN                          (1 << 0)
#define LCD_OSDCTRL                             REG16(LCD_ADDR + 0x104)
#define LCD_OSDCTRL_IPU                         (1 << 15)
#define LCD_OSDCTRL_RGB555                      (1 << 4)
#define LCD_OSDCTRL_CHANGES                     (1 << 3)
#define LCD_OSDCTRL_OSDBPP_bm                   (7 << 0)
#define LCD_OSDCTRL_OSDBPP(v)                   (((v) & 7) << 0)
#define LCD_OSDCTRL_OSDBPP_v(v)                 ((LCD_OSDCTRL_OSDBPP_##v & 7) << 0)
#define LCD_OSDCTRL_OSDBPP_get(v)               (((v) >> 0) & 7)
#define LCD_OSDCTRL_OSDBPP_2                    1
#define LCD_OSDCTRL_OSDBPP_4                    2
#define LCD_OSDCTRL_OSDBPP_15_16                4
#define LCD_OSDCTRL_OSDBPP_16                   4
#define LCD_OSDCTRL_OSDBPP_18_24                5
#define LCD_OSDCTRL_OSDBPP_CMPS_24              6
#define LCD_OSDCTRL_OSDBPP_30                   7
#define LCD_OSDS                                REG16(LCD_ADDR + 0x108)
#define LCD_OSDS_SOF1                           (1 << 15)
#define LCD_OSDS_EOF1                           (1 << 14)
#define LCD_OSDS_SOF0                           (1 << 11)
#define LCD_OSDS_EOF0                           (1 << 10)
#define LCD_OSDS_READY                          (1 << 0)
#define LCD_BGC                                 REG32(LCD_ADDR + 0x10c)
#define LCD_BGC_RED_bm                          (0xff << 16)
#define LCD_BGC_RED(v)                          (((v) & 0xff) << 16)
#define LCD_BGC_RED_get(v)                      (((v) >> 16) & 0xff)
#define LCD_BGC_GREEN_bm                        (0xff << 8)
#define LCD_BGC_GREEN(v)                        (((v) & 0xff) << 8)
#define LCD_BGC_GREEN_get(v)                    (((v) >> 8) & 0xff)
#define LCD_BGC_BLUE_bm                         (0xff << 0)
#define LCD_BGC_BLUE(v)                         (((v) & 0xff) << 0)
#define LCD_BGC_BLUE_get(v)                     (((v) >> 0) & 0xff)
#define LCD_KEY(n)                              REG32(LCD_ADDR + 0x110 + (n) * 0x4)
#define LCD_KEY_KEYEN                           (1 << 31)
#define LCD_KEY_KEYMD                           (1 << 30)
#define LCD_KEY_RED_bm                          (0xff << 16)
#define LCD_KEY_RED(v)                          (((v) & 0xff) << 16)
#define LCD_KEY_RED_get(v)                      (((v) >> 16) & 0xff)
#define LCD_KEY_GREEN_bm                        (0xff << 8)
#define LCD_KEY_GREEN(v)                        (((v) & 0xff) << 8)
#define LCD_KEY_GREEN_get(v)                    (((v) >> 8) & 0xff)
#define LCD_KEY_BLUE_bm                         (0xff << 0)
#define LCD_KEY_BLUE(v)                         (((v) & 0xff) << 0)
#define LCD_KEY_BLUE_get(v)                     (((v) >> 0) & 0xff)
#define LCD_ALPHA                               REG8(LCD_ADDR + 0x118)
#define LCD_IPUR                                REG32(LCD_ADDR + 0x11c)
#define LCD_IPUR_IPUREN                         (1 << 31)
#define LCD_XYP(n)                              REG32(LCD_ADDR + 0x120 + (n) * 0x4)
#define LCD_XYP_YPOS_bm                         (0xffff << 16)
#define LCD_XYP_YPOS(v)                         (((v) & 0xffff) << 16)
#define LCD_XYP_YPOS_get(v)                     (((v) >> 16) & 0xffff)
#define LCD_XYP_XPOS_bm                         (0xffff << 0)
#define LCD_XYP_XPOS(v)                         (((v) & 0xffff) << 0)
#define LCD_XYP_XPOS_get(v)                     (((v) >> 0) & 0xffff)
#define LCD_SIZE(n)                             REG32(LCD_ADDR + 0x128 + (n) * 0x4)
#define LCD_DA0_PART2                           REG32(LCD_ADDR + 0x1c0)
#define LCD_SA0_PART2                           REG32(LCD_ADDR + 0x1c4)
#define LCD_FID0_PART2                          REG32(LCD_ADDR + 0x1c8)
#define LCD_CMD0_PART2                          REG32(LCD_ADDR + 0x1cc)
#define LCD_OFFS0_PART2                         REG32(LCD_ADDR + 0x1e0)
#define LCD_PW0_PART2                           REG32(LCD_ADDR + 0x1e4)
#define LCD_CNUM0_PART2                         REG32(LCD_ADDR + 0x1e8)
#define LCD_DESSIZE0_PART2                      REG32(LCD_ADDR + 0x1ec)
#define LCD_XYP0_PART2                          REG32(LCD_ADDR + 0x1f0)
#define LCD_SIZE0_PART2                         REG32(LCD_ADDR + 0x1f4)
#define LCD_PCFG                                REG32(LCD_ADDR + 0x2c0)

#define SLCD_ADDR                               0xb3050000
#define SLCD_MCFG                               REG32(SLCD_ADDR + 0xa0)
#define SLCD_MCFG_DATA_WIDTH_bm                 (7 << 10)
#define SLCD_MCFG_DATA_WIDTH(v)                 (((v) & 7) << 10)
#define SLCD_MCFG_DATA_WIDTH_v(v)               ((SLCD_MCFG_DATA_WIDTH_##v & 7) << 10)
#define SLCD_MCFG_DATA_WIDTH_get(v)             (((v) >> 10) & 7)
#define SLCD_MCFG_DATA_WIDTH_18BIT              0
#define SLCD_MCFG_DATA_WIDTH_16BIT              1
#define SLCD_MCFG_DATA_WIDTH_8BIT_x3            2
#define SLCD_MCFG_DATA_WIDTH_8BIT_x2            3
#define SLCD_MCFG_DATA_WIDTH_8BIT_x1            4
#define SLCD_MCFG_DATA_WIDTH_24BIT              5
#define SLCD_MCFG_DATA_WIDTH_9BIT_x2            7
#define SLCD_MCFG_CMD_WIDTH_bm                  (3 << 8)
#define SLCD_MCFG_CMD_WIDTH(v)                  (((v) & 3) << 8)
#define SLCD_MCFG_CMD_WIDTH_v(v)                ((SLCD_MCFG_CMD_WIDTH_##v & 3) << 8)
#define SLCD_MCFG_CMD_WIDTH_get(v)              (((v) >> 8) & 3)
#define SLCD_MCFG_CMD_WIDTH_16BIT               0
#define SLCD_MCFG_CMD_WIDTH_8BIT                1
#define SLCD_MCFG_CMD_WIDTH_18BIT               2
#define SLCD_MCFG_CMD_WIDTH_24BIT               3
#define SLCD_MCFG_CS_ACTIVE_HIGH                (1 << 4)
#define SLCD_MCFG_RS_CMD_HIGH                   (1 << 3)
#define SLCD_MCFG_CLK_ACTIVE_RISING             (1 << 1)
#define SLCD_MCFG_TYPE_SERIAL                   (1 << 0)
#define SLCD_MCTRL                              REG8(SLCD_ADDR + 0xa4)
#define SLCD_MCTRL_DMA_MODE                     (1 << 2)
#define SLCD_MCTRL_DMA_START                    (1 << 1)
#define SLCD_MCTRL_DMA_EN                       (1 << 0)
#define SLCD_MSTATE                             REG8(SLCD_ADDR + 0xa8)
#define SLCD_MSTATE_BUSY                        (1 << 0)
#define SLCD_MDATA                              REG32(SLCD_ADDR + 0xac)
#define SLCD_MDATA_RS                           (1 << 31)

#endif /* __HEADERGEN_JZ4760B_H__*/
