#ifndef __USB_DESIGNWARE_REGS_H__
#define __USB_DESIGNWARE_REGS_H__

#include "config.h"

/* Global registers */
#define DESIGNWARE_GOTGCTL (*((uint32_t volatile*)(OTGBASE + 0x00)))
#define DESIGNWARE_GOTGINT (*((uint32_t volatile*)(OTGBASE + 0x04)))
#define DESIGNWARE_GAHBCFG (*((uint32_t volatile*)(OTGBASE + 0x08)))
    #define PTXFELVL (1<<8)
    #define TXFELVL (1<<7)
    #define DMAEN (1<<5)
    #define HBSTLEN(x) ((x)<<1)
    #define GINT (1<<0)
    
#define DESIGNWARE_GUSBCFG (*((uint32_t volatile*)(OTGBASE + 0x0c)))
    #define FDMOD (1<<30)
    #define TRDT(x) ((x)<<10)
    #define PHSEL (1<<6)
    #define ULPI_UTMI_SEL (1<<4)
    #define PHYIF16 (1<<3)

#define DESIGNWARE_GRSTCTL (*((uint32_t volatile*)(OTGBASE + 0x10)))
    #define AHBIDL (1<<31)
    #define GRSTCTL_TXFNUM(x) ((x)<<6)
    #define TXFFLSH (1<<5)
    #define CSRST (1<<0)
    
#define DESIGNWARE_GINTSTS (*((uint32_t volatile*)(OTGBASE + 0x14)))
    #define WKUINT (1<<31)
    #define SRQINT (1<<30)
    #define DISCINT (1<<29)
    #define CIDSCHG (1<<28)
    #define PTXFE (1<<26)
    #define HCINT (1<<25)
    #define HPRTINT (1<<24)
    #define IPXFR (1<<21)
    #define IISOIXFR (1<<20)
    #define OEPINT (1<<19)
    #define IEPINT (1<<18)
    #define EOPF (1<<15)
    #define ISOODPR (1<<14)
    #define ENUMDNE (1<<13)
    #define USBRST (1<<12)
    #define USBSUSP (1<<11)
    #define ESUSP (1<<10)
    #define GOUTNAKEFF (1<<7)
    #define GINAKEFF (1<<6)
    #define NPTXFE (1<<5)
    #define RXFLVL (1<<4)
    #define SOF (1<<3)
    #define OTGINT (1<<2)
    #define MMIS (1<<1)
    #define CMOD (1<<0)

#define DESIGNWARE_GINTMSK (*((uint32_t volatile*)(OTGBASE + 0x18)))
#define DESIGNWARE_GRXSTSR (*((uint32_t volatile*)(OTGBASE + 0x1c)))
#define DESIGNWARE_GRXSTSP (*((uint32_t volatile*)(OTGBASE + 0x20)))
#define DESIGNWARE_GRXFSIZ (*((uint32_t volatile*)(OTGBASE + 0x24)))
#define DESIGNWARE_GNPTXFSIZ_TX0FSIZ (*((uint32_t volatile*)(OTGBASE + 0x28)))
#define DESIGNWARE_GNPTXSTS (*((uint32_t volatile*)(OTGBASE + 0x2c)))
#define DESIGNWARE_GI2CCTL (*((uint32_t volatile*)(OTGBASE + 0x30)))
/* reserved */
#define DESIGNWARE_GCCFG (*((uint32_t volatile*)(OTGBASE + 0x38)))
    #define NOVBUSSENS (1<<21)
    #define SOFOUTEN (1<<20)
    #define VBUSBSEN (1<<19)
    #define VBUSASEN (1<<18)
    #define I2CPADEN (1<<17)
    #define PWRDWN (1<<16)

#define DESIGNWARE_CID (*((uint32_t volatile*)(OTGBASE + 0x3c)))
#define DESIGNWARE_GSNPSID (*((uint32_t volatile*)(OTGBASE + 0x40)))
#define DESIGNWARE_GHWCFG1 (*((uint32_t volatile*)(OTGBASE + 0x44)))
#define DESIGNWARE_GHWCFG2 (*((uint32_t volatile*)(OTGBASE + 0x48)))
#define DESIGNWARE_GHWCFG3 (*((uint32_t volatile*)(OTGBASE + 0x4c)))
#define DESIGNWARE_GHWCFG4 (*((uint32_t volatile*)(OTGBASE + 0x50)))
#define DESIGNWARE_GLPMCFG (*((uint32_t volatile*)(OTGBASE + 0x54)))
#define DESIGNWARE_HPTXFSIZ (*((uint32_t volatile*)(OTGBASE + 0x100)))
#define DESIGNWARE_DIEPTXF(x) (*((uint32_t volatile*)(OTGBASE + 0x104 + 4*(x)))) //dieptxf[15]

/* Host mode registers */
#define DESIGNWARE_HCFG (*((uint32_t volatile*)(OTGBASE + 0x400)))
#define DESIGNWARE_HFIR (*((uint32_t volatile*)(OTGBASE + 0x404)))
#define DESIGNWARE_HFNUM (*((uint32_t volatile*)(OTGBASE + 0x408)))
/* reserved */
#define DESIGNWARE_HPTXSTS (*((uint32_t volatile*)(OTGBASE + 0x410)))
#define DESIGNWARE_HAINT (*((uint32_t volatile*)(OTGBASE + 0x414)))
#define DESIGNWARE_HAINTMSK (*((uint32_t volatile*)(OTGBASE + 0x418)))
#define DESIGNWARE_HPRT (*((uint32_t volatile*)(OTGBASE + 0x440)))
#define DESIGNWARE_HCCHAR(x) (*((uint32_t volatile*)(OTGBASE + 0x500 + 0x20*(x))))
#define DESIGNWARE_HCSPLT(x) (*((uint32_t volatile*)(OTGBASE + 0x504 + 0x20*(x))))
#define DESIGNWARE_HCINT(x) (*((uint32_t volatile*)(OTGBASE + 0x508 + 0x20*(x))))
#define DESIGNWARE_HCINTMSK(x) (*((uint32_t volatile*)(OTGBASE + 0x50c + 0x20*(x))))
#define DESIGNWARE_HCTSIZ(x) (*((uint32_t volatile*)(OTGBASE + 0x510 + 0x20*(x))))
#define DESIGNWARE_HCDMA(x) (*((uint32_t volatile*)(OTGBASE + 0x514 + 0x20*(x))))

/* Device mode registers */
#define DESIGNWARE_DCFG (*((uint32_t volatile*)(OTGBASE + 0x800)))
    #define DAD(x) ((x)<<4)
    #define NZLSOHSK (1<<2)
    
#define DESIGNWARE_DCTL (*((uint32_t volatile*)(OTGBASE + 0x804)))
    #define POPRGDNE (1<<11)
    #define CGONAK (1<<10)
    #define SGONAK (1<<9)
    #define CGINAK (1<<8)
    #define TCTL(x) ((x)<<4)
    #define GONSTS (1<<3)
    #define GINSTS (1<<2)
    #define SDIS (1<<1)
    #define RWUSIG (1<<0)

#define DESIGNWARE_DSTS (*((uint32_t volatile*)(OTGBASE + 0x808)))
/* reserved */
#define DESIGNWARE_DIEPMSK (*((uint32_t volatile*)(OTGBASE + 0x810)))
#define DESIGNWARE_DOEPMSK (*((uint32_t volatile*)(OTGBASE + 0x814)))
#define DESIGNWARE_DAINT (*((uint32_t volatile*)(OTGBASE + 0x818)))
#define DESIGNWARE_DAINTMSK (*((uint32_t volatile*)(OTGBASE + 0x81c)))
/* reserved */
#define DESIGNWARE_DVBUSDIS (*((uint32_t volatile*)(OTGBASE + 0x828)))
#define DESIGNWARE_DVBUSPULSE (*((uint32_t volatile*)(OTGBASE + 0x82c)))
#define DESIGNWARE_DTHRCTL (*((uint32_t volatile*)(OTGBASE + 0x830)))
    #define ARPEN (1<<27)
    #define RXTHRLEN(x) ((x)<<17)
    #define RXTHREN (1<<16)
    #define TXTHRLEN(x) ((x)<<2)
    #define ISOTHREN (1<<1)
    #define NONISOTHREN (1<<0)

#define DESIGNWARE_DIEPEMPMSK (*((uint32_t volatile*)(OTGBASE + 0x834)))
#define DESIGNWARE_DEACHINT (*((uint32_t volatile*)(OTGBASE + 0x838)))
#define DESIGNWARE_DEACHINTMSK (*((uint32_t volatile*)(OTGBASE + 0x83c)))
#define DESIGNWARE_DIEPEACHMSK1 (*((uint32_t volatile*)(OTGBASE + 0x844)))
#define DESIGNWARE_DOEPEACHMSK1 (*((uint32_t volatile*)(OTGBASE + 0x884)))

#define DESIGNWARE_DIEPCTL(x) (*((uint32_t volatile*)(OTGBASE + 0x920 + 0x20*(x))))
    #define DTXFNUM(x) ((x)<<22)
    #define STALL (1<<21)
    #define EPTYP(x) ((x)<<18)
    #define NAKSTS (1<<17)
    #define USBAEP (1<<15)
    #define NEXTEP(x) ((x)<<11)

#define DESIGNWARE_DIEPINT(x) (*((uint32_t volatile*)(OTGBASE + 0x908 + 0x20*(x))))
    #define TXFE (1<<7)
    #define INEPNE (1<<6)
    #define ITTXFE (1<<4)
    #define TOC (1<<3)
    #define XFRC (1<<0)
    
#define DESIGNWARE_DIEPTSIZ(x) (*((uint32_t volatile*)(OTGBASE + 0x910 + 0x20*(x))))
#define DESIGNWARE_DIEPDMA(x) (*((uint32_t volatile*)(OTGBASE + 0x914 + 0x20*(x))))
#define DESIGNWARE_DTXFSTS(x) (*((uint32_t volatile*)(OTGBASE + 0x918 + 0x20*(x))))

#define DESIGNWARE_DOEPCTL(x) (*((uint32_t volatile*)(OTGBASE + 0xb00 + 0x20*(x))))
    #define EPENA (1<<31)
    #define EPDIS (1<<30)
    #define SD0PID (1<<28)
    #define SNAK (1<<27)
    #define CNAK (1<<26)

#define DESIGNWARE_DOEPINT(x) (*((uint32_t volatile*)(OTGBASE + 0xb08 + 0x20*(x))))
    #define STUP (1<<3)
    #define EPDISD (1<<1)

#define DESIGNWARE_DOEPTSIZ(x) (*((uint32_t volatile*)(OTGBASE + 0xb10 + 0x20*(x))))
    #define STUPCNT(x) ((x)<<29)
    #define PKTCNT(x) ((x)<<19)
    
#define DESIGNWARE_DOEPDMA(x) (*((uint32_t volatile*)(OTGBASE + 0xb14 + 0x20*(x))))
#define DESIGNWARE_PCGCCTL (*((uint32_t volatile*)(OTGBASE + 0xe00)))
#define DESIGNWARE_DFIFO(x) (*((uint32_t volatile*)(OTGBASE + 0x1000 + 0x1000*(x))))

#endif
