#ifndef __BUILD_AUTOCONF_H
#define __BUILD_AUTOCONF_H

#define __PCTOOL__
#define CONFIG_CODEC SWCODEC
#define TARGET_ID 73 /* sdlapp */
#define MEMORYSIZE 64
#define ROCKBOX_LITTLE_ENDIAN 1
#define HAVE_PITCHSCREEN
#define HAVE_SW_TONE_CONTROLS
#define HAVE_SW_VOLUME_CONTROL
#define VOLUME_MIN -100
#define VOLUME_MAX 100
#define SW_VOLUME_MIN -100
#define SW_VOLUME_MAX 100

#endif /* __BUILD_AUTOCONF_H */
