#!/bin/sh

######################################################################
#             __________               __   ___.
#   Open      \______   \ ____   ____ |  | _\_ |__   _______  ___
#   Source     |       _//  _ \_/ ___\|  |/ /| __ \ /  _ \  \/  /
#   Jukebox    |    |   (  <_> )  \___|    < | \_\ (  <_> > <  <
#   Firmware   |____|_  /\____/ \___  >__|_ \|___  /\____/__/\_ \
#                     \/            \/     \/    \/            \/
#
#   * Safe Mode for Samsung YP-Q2 platform
#   * Copyright (C) 2017 Lorenzo Miori
######################################################################


MODE="normal"
RESOURCE_PATH="/appfs/safemode"
#RESOURCE_PATH="/mnt/usb/safemode"

if [ $# -eq 1 ]
then
    MODE=$1
fi

power_pressed()
{
    # I haven't managed to find a "cleaner" way to get button presses
    # It is furthermore the only wait to get the buttons at power-up
    # due to the fact that touch buttons are only detected on an interrupt basis
    # i.e. not detectable if already pressed !
    dmesg | tail -n 1 | grep "POWER button pressed"
    return $?
}

back_pressed()
{
    # I haven't managed to find a "cleaner" way to get button presses
    # It is furthermore the only wait to get the buttons at power-up
    # due to the fact that touch buttons are only detected on an interrupt basis
    # i.e. not detectable if already pressed !
    # PLEASE NOTE the subtle difference between this and power_pressed():
    # we do NOT know the position of such string in the dmesg log at boot...
    dmesg | grep "USER button pressed"
    return $?
}

cable_disconnected()
{
    # Error code 0 when disconnected
    cat /proc/usbevent | grep disconnected
    return $?
}

enable_display()
{
    # set automatic refresh (enable DMA work)
    # nothing to do on YP-Z5
    echo "NOP" > /dev/null
}

display_image()
{
    # /dev/fb is not available for writing without
    # opening the framebuffer for some reason and
    # we also need to issue a ioctl call to flush
    # the soft-buffer to the display memory
    $RESOURCE_PATH/fb_write $1
}

if [ $MODE != "forced" ]
then
    back_pressed
    if [ $? -eq 1 ]
    then
      # do not enter safe mode and continue normal boot
        exit 0
    fi
fi

# Here we entered safe mode, so first clean the display
# and turn on backlight at minimum level
enable_display

# there are different ROMs around...
DefIMG="$RESOURCE_PATH/usbmode.raw"
RbtIMG="$RESOURCE_PATH/usbmode_post.raw"
PreIMG="$RESOURCE_PATH/usbmode_pre.raw"

NOUSB=true

if cable_disconnected
then

    display_image $PreIMG

    while $NOUSB
    do

        # User aborts safe mode before mounting anything, just exit
        # and continue normal boot
        if power_pressed
        then
            sleep 1
            if power_pressed
            then
                exit 1
            fi
        fi

        if cable_disconnected
        then
            echo "USB not connected - Waiting"
        else
            sleep 1
            if cable_disconnected
            then
                echo "USB first check OK - Waiting"
            else
                sleep 1
                if cable_disconnected
                then
                    echo "USB second check OK - Waiting"
                else
                    NOUSB=false
                    USB=true
                fi
            fi
        fi
    done
else
    while $NOUSB
    do
        if cable_disconnected
        then
            echo "USB not connected - Waiting"
        else
            sleep 1
            if cable_disconnected
            then
                echo "USB first check OK - Waiting"
            else
                NOUSB=false
                USB=true
            fi
        fi
    done
fi

display_image $DefIMG

echo "Enabling USB storage"
/appfs/bin/runusb.sh
/bin/msc on

SAFE=true
while $SAFE
do
    if power_pressed
    then
        sleep 1
        if power_pressed
        then
            SAFE=false
        fi
    fi
    # add also unmount of device
done

echo "Disabling USB storage"
/bin/msc off

display_image $RbtIMG

USB=true

while $USB
do
    if cable_disconnected
    then
        sleep 1
        if cable_disconnected
        then
            if cable_disconnected
            then
                sleep 1
                if cable_disconnected
                then
                    USB=false
                else
                    echo "USB connected - Waiting"
                    USB=true
                fi
            else
                echo "USB connected - Waiting"
                USB=true
            fi
        else
            echo "USB connected - Waiting"
            USB=true
        fi
    else
        echo "USB connected - Waiting"
        USB=true
    fi
done

#power key pressed for almost 2 sec and cable disconnected. Power off!
exit 1
