CFLAGS = -Wall -O3 -I../lib -DTEST -D"DEBUGF=printf" -D"ROCKBOX_LITTLE_ENDIAN=1" -D"ICONST_ATTR=" -D"ICODE_ATTR=" -D"IBSS_ATTR="
OBJS = atrac3.o ../lib/ffmpeg_bitstream.o ../librm/rm.o fixp_math.o ../lib/mdct2.o ../lib/mdct_lookup.o main.o

atractest: $(OBJS)
	gcc -o atractest $(OBJS)

.c.o :
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f atractest $(OBJS) *~ output.wav
