CFLAGS = -Wall -O3 -I../lib -DTEST -D"DEBUGF=printf" -D"ROCKBOX_LITTLE_ENDIAN=1" -D"ICONST_ATTR=" -D"ICODE_ATTR="
OBJS = main.o ../lib/ffmpeg_bitstream.o cook.o ../librm/rm.o ../lib/mdct2.o ../lib/mdct_lookup.o
cooktest: $(OBJS)
	gcc -o cooktest $(OBJS)

.c.o :
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f cooktest $(OBJS) *~ output.wav
