/* Generated by bin2c */

<<<<<<< HEAD
extern unsigned char dualboot_fuzeplus[460];
extern unsigned char dualboot_zenxfi2[328];
extern unsigned char dualboot_zenxfi3[288];
extern unsigned char dualboot_nwze370[676];
extern unsigned char dualboot_nwze360[676];
extern unsigned char dualboot_zenxfistyle[376];
=======
extern unsigned char dualboot_fuzeplus[228];
extern unsigned char dualboot_zenxfi2[96];
extern unsigned char dualboot_zenxfi3[56];
extern unsigned char dualboot_nwze370[416];
extern unsigned char dualboot_nwze360[416];
extern unsigned char dualboot_zenmx[24];
>>>>>>> Initial commit for the Creative ZEN MX
