/* Generated by bin2c */

extern unsigned char dualboot_fuzeplus[728];
extern unsigned char dualboot_zenxfi2[608];
extern unsigned char dualboot_zenxfi3[572];
extern unsigned char dualboot_nwze370[896];
extern unsigned char dualboot_nwze360[944];
extern unsigned char dualboot_zenxfistyle[660];
