/* Generated by bin2c */

extern unsigned char dualboot_fuzeplus[460];
extern unsigned char dualboot_zenxfi2[328];
extern unsigned char dualboot_zenxfi3[288];
extern unsigned char dualboot_nwze370[644];
extern unsigned char dualboot_nwze360[644];
extern unsigned char dualboot_zenxfistyle[360];
