#ifndef __LANGUAGE_H
#define __LANGUAGE_H
/***************************************************************************
 *             __________               __   ___.
 *   Open      \______   \ ____   ____ |  | _\_ |__   _______  ___
 *   Source     |       _//  _ \_/ ___\|  |/ /| __ \ /  _ \  \/  /
 *   Jukebox    |    |   (  <_> )  \___|    < | \_\ (  <_> > <  <
 *   Firmware   |____|_  /\____/ \___  >__|_ \|___  /\____/__/\_ \
 *                     \/            \/     \/    \/            \/
 * $Id$
 *
 * Copyright (C) 2002, 2008 Daniel Stenberg
 *
 * All files in this archive are subject to the GNU General Public License.
 * See the file COPYING in the source tree root for full license agreement.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 ****************************************************************************/

/* The following header is generated by the build system and only defines
   MAX_LANGUAGE_SIZE to be the size of the largest currently available
   language! */
//#include "max_language_size.h"

/* size of the buffer used for loadable, translated strings */
#define MAX_LANGUAGE_SIZE 23500

/* both these must match the two initial bytes in the binary lang file */
#define LANGUAGE_COOKIE  0x1a
#define LANGUAGE_VERSION 0x04

/* Initialize language array with the builtin strings */
void lang_init(void);

/* load a given language file */
int lang_load(const char *filename);

#endif
