#
# common
#
CC=mipsel-elf-gcc
LD=mipsel-elf-gcc
AS=mipsel-elf-gcc
OC=mipsel-elf-objcopy
DEFINES=
INCLUDES=-I$(CURDIR)
GCCOPTS=-march=4kec -G0 -msoft-float
BUILD_DIR=$(CURDIR)/build/
ROOT_DIR=$(CURDIR)/..

include ../hwstub.make
