/* Generated by bin2c */

extern unsigned char nrv2e_d8[168];
extern unsigned char dualboot_clip[196];
extern unsigned char dualboot_e200v2[176];
extern unsigned char dualboot_c200v2[272];
extern unsigned char dualboot_m200v4[180];
extern unsigned char dualboot_fuze[176];
extern unsigned char dualboot_clipv2[240];
extern unsigned char dualboot_clipplus[184];
extern unsigned char dualboot_fuzev2[176];
extern unsigned char dualboot_clipzip[232];
