/* Generated by bin2c */

extern unsigned char nrv2e_d8[168];
extern unsigned char dualboot_clip[224];
extern unsigned char dualboot_e200v2[204];
extern unsigned char dualboot_c200v2[400];
extern unsigned char dualboot_m200v4[180];
extern unsigned char dualboot_fuze[204];
extern unsigned char dualboot_clipv2[248];
extern unsigned char dualboot_clipplus[340];
extern unsigned char dualboot_fuzev2[332];
