/* Generated by bin2c */

extern unsigned char nrv2e_d8[168];
extern unsigned char dualboot_clip[248];
extern unsigned char dualboot_e200v2[228];
extern unsigned char dualboot_c200v2[228];
extern unsigned char dualboot_m200v4[204];
extern unsigned char dualboot_fuze[228];
extern unsigned char dualboot_clipv2[272];
extern unsigned char dualboot_clipplus[256];
