/* button definitions */
#if (CONFIG_KEYPAD == IRIVER_H100_PAD) || (CONFIG_KEYPAD == IRIVER_H300_PAD)
#define BTN_MENU       BUTTON_MODE
#define BTN_STOP       BUTTON_OFF
#define BTN_PAUSE      BUTTON_ON
#define BTN_VOLDOWN    BUTTON_DOWN
#define BTN_VOLUP      BUTTON_UP
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT

#elif (CONFIG_KEYPAD == IPOD_4G_PAD) || (CONFIG_KEYPAD == IPOD_3G_PAD) || \
      (CONFIG_KEYPAD == IPOD_1G2G_PAD)
#define BTN_MENU       BUTTON_MENU
#define BTN_PAUSE      (BUTTON_PLAY | BUTTON_REL)
#define BTN_STOP       (BUTTON_PLAY | BUTTON_REPEAT)
#define BTN_VOLDOWN    BUTTON_SCROLL_BACK
#define BTN_VOLUP      BUTTON_SCROLL_FWD
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT

#elif CONFIG_KEYPAD == IAUDIO_X5M5_PAD
#define BTN_MENU       (BUTTON_REC | BUTTON_REL)
#define BTN_STOP       BUTTON_POWER
#define BTN_PAUSE      BUTTON_PLAY
#define BTN_VOLDOWN    BUTTON_DOWN
#define BTN_VOLUP      BUTTON_UP
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT

#elif CONFIG_KEYPAD == GIGABEAT_PAD
#define BTN_MENU       BUTTON_MENU
#define BTN_STOP       BUTTON_POWER
#define BTN_PAUSE      BUTTON_SELECT
#define BTN_PAUSE2     BUTTON_A
#define BTN_VOLDOWN    BUTTON_LEFT
#define BTN_VOLUP      BUTTON_RIGHT
#define BTN_VOLDOWN2   BUTTON_VOL_DOWN
#define BTN_VOLUP2     BUTTON_VOL_UP
#define BTN_RW         BUTTON_UP
#define BTN_FF         BUTTON_DOWN

#define BTN_RC_MENU    BUTTON_RC_DSP
#define BTN_RC_STOP    (BUTTON_RC_PLAY | BUTTON_REPEAT)
#define BTN_RC_PAUSE   (BUTTON_RC_PLAY | BUTTON_REL)
#define BTN_RC_VOLDOWN BUTTON_RC_VOL_DOWN
#define BTN_RC_VOLUP   BUTTON_RC_VOL_UP
#define BTN_RC_RW      BUTTON_RC_REW
#define BTN_RC_FF      BUTTON_RC_FF

#elif CONFIG_KEYPAD == GIGABEAT_S_PAD
#define BTN_MENU       BUTTON_MENU
#define BTN_STOP       BUTTON_POWER
#define BTN_PAUSE      BUTTON_SELECT
#define BTN_PAUSE2     BUTTON_PLAY
#define BTN_VOLDOWN    BUTTON_LEFT
#define BTN_VOLUP      BUTTON_RIGHT
#define BTN_VOLDOWN2   BUTTON_VOL_DOWN
#define BTN_VOLUP2     BUTTON_VOL_UP
#define BTN_RW         BUTTON_UP
#define BTN_RW2        BUTTON_PREV
#define BTN_FF         BUTTON_DOWN
#define BTN_FF2        BUTTON_NEXT
#define BTN_SHOW_OSD   BUTTON_BACK

#define BTN_RC_MENU    BUTTON_RC_DSP
#define BTN_RC_STOP    (BUTTON_RC_PLAY | BUTTON_REPEAT)
#define BTN_RC_PAUSE   (BUTTON_RC_PLAY | BUTTON_REL)
#define BTN_RC_VOLDOWN BUTTON_RC_VOL_DOWN
#define BTN_RC_VOLUP   BUTTON_RC_VOL_UP
#define BTN_RC_RW      BUTTON_RC_REW
#define BTN_RC_FF      BUTTON_RC_FF

#elif CONFIG_KEYPAD == IRIVER_H10_PAD
#define BTN_MENU       BUTTON_LEFT
#define BTN_STOP       BUTTON_POWER
#define BTN_PAUSE      BUTTON_PLAY
#define BTN_VOLDOWN    BUTTON_SCROLL_DOWN
#define BTN_VOLUP      BUTTON_SCROLL_UP
#define BTN_RW         BUTTON_REW
#define BTN_FF         BUTTON_FF

#elif CONFIG_KEYPAD == SANSA_E200_PAD
#define BTN_MENU       BUTTON_SELECT
#define BTN_STOP       BUTTON_POWER
#define BTN_PAUSE      BUTTON_RIGHT
#define BTN_VOLDOWN    BUTTON_SCROLL_BACK
#define BTN_VOLUP      BUTTON_SCROLL_FWD
#define BTN_RW         BUTTON_UP
#define BTN_FF         BUTTON_DOWN

#elif CONFIG_KEYPAD == SANSA_FUZE_PAD
#define BTN_MENU       BUTTON_SELECT
#define BTN_STOP       (BUTTON_HOME|BUTTON_REPEAT)
#define BTN_PAUSE      BUTTON_UP
#define BTN_VOLDOWN    BUTTON_SCROLL_BACK
#define BTN_VOLUP      BUTTON_SCROLL_FWD
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT


#elif CONFIG_KEYPAD == SANSA_C200_PAD || \
CONFIG_KEYPAD == SANSA_CLIP_PAD || \
CONFIG_KEYPAD == SANSA_M200_PAD
#define BTN_MENU       BUTTON_SELECT
#define BTN_STOP       BUTTON_POWER
#define BTN_PAUSE      BUTTON_UP
#define BTN_VOLDOWN    BUTTON_VOL_DOWN
#define BTN_VOLUP      BUTTON_VOL_UP
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT

#elif CONFIG_KEYPAD == MROBE500_PAD
#define BTN_STOP       BUTTON_POWER

#define BTN_RC_MENU    BUTTON_RC_HEART
#define BTN_RC_STOP    BUTTON_RC_DOWN
#define BTN_RC_PAUSE   BUTTON_RC_PLAY
#define BTN_RC_VOLDOWN BUTTON_RC_VOL_DOWN
#define BTN_RC_VOLUP   BUTTON_RC_VOL_UP
#define BTN_RC_RW      BUTTON_RC_REW
#define BTN_RC_FF      BUTTON_RC_FF

#elif CONFIG_KEYPAD == MROBE100_PAD
#define BTN_MENU       BUTTON_MENU
#define BTN_STOP       BUTTON_POWER
#define BTN_PAUSE      BUTTON_PLAY
#define BTN_VOLDOWN    BUTTON_DOWN
#define BTN_VOLUP      BUTTON_UP
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT

#elif CONFIG_KEYPAD == IAUDIO_M3_PAD
#define BTN_MENU       BUTTON_RC_MENU
#define BTN_STOP       BUTTON_RC_REC
#define BTN_PAUSE      BUTTON_RC_PLAY
#define BTN_VOLDOWN    BUTTON_RC_VOL_DOWN
#define BTN_VOLUP      BUTTON_RC_VOL_UP
#define BTN_RW         BUTTON_RC_REW
#define BTN_FF         BUTTON_RC_FF

#elif CONFIG_KEYPAD == COWON_D2_PAD
#define BTN_MENU       (BUTTON_MENU|BUTTON_REL)
//#define BTN_STOP       BUTTON_POWER
#define BTN_VOLDOWN    BUTTON_MINUS
#define BTN_VOLUP      BUTTON_PLUS

#elif CONFIG_KEYPAD == IAUDIO67_PAD
#define BTN_MENU       BUTTON_MENU
#define BTN_STOP       BUTTON_STOP
#define BTN_PAUSE      BUTTON_PLAY
#define BTN_VOLDOWN    BUTTON_VOLDOWN
#define BTN_VOLUP      BUTTON_VOLUP
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT

#elif CONFIG_KEYPAD == CREATIVEZVM_PAD
#define BTN_MENU       BUTTON_MENU
#define BTN_STOP       BUTTON_BACK
#define BTN_PAUSE      BUTTON_PLAY
#define BTN_VOLDOWN    BUTTON_UP
#define BTN_VOLUP      BUTTON_DOWN
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT

#elif CONFIG_KEYPAD ==  CREATIVE_ZENXFI3_PAD
#define BTN_MENU       BUTTON_MENU
#define BTN_STOP       (BUTTON_PLAY|BUTTON_REPEAT)
#define BTN_PAUSE      (BUTTON_PLAY|BUTTON_REL)
#define BTN_VOLDOWN    BUTTON_VOL_DOWN
#define BTN_VOLUP      BUTTON_VOL_UP
#define BTN_RW         BUTTON_DOWN
#define BTN_FF         BUTTON_UP

#elif CONFIG_KEYPAD == PHILIPS_HDD1630_PAD
#define BTN_MENU       BUTTON_MENU
#define BTN_STOP       BUTTON_POWER
#define BTN_PAUSE      BUTTON_SELECT
#define BTN_VOLDOWN    BUTTON_VOL_DOWN
#define BTN_VOLUP      BUTTON_VOL_UP
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT

#elif CONFIG_KEYPAD == PHILIPS_HDD6330_PAD
#define BTN_MENU       BUTTON_MENU
#define BTN_STOP       BUTTON_POWER
#define BTN_PAUSE      BUTTON_PLAY
#define BTN_VOLDOWN    BUTTON_VOL_DOWN
#define BTN_VOLUP      BUTTON_VOL_UP
#define BTN_RW         BUTTON_PREV
#define BTN_FF         BUTTON_NEXT

#elif CONFIG_KEYPAD == PHILIPS_SA9200_PAD
#define BTN_MENU       BUTTON_MENU
#define BTN_STOP       BUTTON_POWER
#define BTN_PAUSE      BUTTON_PLAY
#define BTN_VOLDOWN    BUTTON_VOL_DOWN
#define BTN_VOLUP      BUTTON_VOL_UP
#define BTN_RW         BUTTON_UP
#define BTN_FF         BUTTON_DOWN

#elif CONFIG_KEYPAD == ONDAVX747_PAD
#define BTN_MENU       (BUTTON_MENU|BUTTON_REL)
//#define BTN_STOP       BUTTON_POWER
#define BTN_VOLDOWN    BUTTON_VOL_DOWN
#define BTN_VOLUP      BUTTON_VOL_UP

#elif CONFIG_KEYPAD == ONDAVX777_PAD
#define BTN_MENU       BUTTON_POWER

#elif (CONFIG_KEYPAD == SAMSUNG_YH820_PAD) || \
      (CONFIG_KEYPAD == SAMSUNG_YH92X_PAD)
#define BTN_MENU       BUTTON_REW
#define BTN_STOP       (BUTTON_PLAY | BUTTON_REPEAT)
#define BTN_PAUSE      (BUTTON_PLAY | BUTTON_REL)
#define BTN_VOLDOWN    BUTTON_DOWN
#define BTN_VOLUP      BUTTON_UP
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT
#define BTN_SHOW_OSD   BUTTON_FFWD

#elif CONFIG_KEYPAD == PBELL_VIBE500_PAD
#define BTN_MENU       BUTTON_MENU
#define BTN_STOP       BUTTON_REC
#define BTN_PAUSE      BUTTON_PLAY
#define BTN_VOLDOWN    BUTTON_DOWN
#define BTN_VOLUP      BUTTON_UP
#define BTN_RW         BUTTON_PREV
#define BTN_FF         BUTTON_NEXT

#elif CONFIG_KEYPAD == MPIO_HD200_PAD
#define BTN_MENU       BUTTON_FUNC
#define BTN_PAUSE      (BUTTON_PLAY | BUTTON_REL)
#define BTN_STOP       (BUTTON_PLAY | BUTTON_REPEAT)
#define BTN_VOLDOWN    BUTTON_VOL_DOWN
#define BTN_VOLUP      BUTTON_VOL_UP
#define BTN_RW         BUTTON_REW
#define BTN_FF         BUTTON_FF

#elif CONFIG_KEYPAD == MPIO_HD300_PAD
#define BTN_MENU       BUTTON_MENU
#define BTN_PAUSE      (BUTTON_PLAY | BUTTON_REL)
#define BTN_STOP       (BUTTON_PLAY | BUTTON_REPEAT)
#define BTN_VOLDOWN    BUTTON_DOWN
#define BTN_VOLUP      BUTTON_UP
#define BTN_RW         BUTTON_REW
#define BTN_FF         BUTTON_FF

#elif CONFIG_KEYPAD == SANSA_FUZEPLUS_PAD
#define BTN_MENU       BUTTON_POWER
#define BTN_PAUSE      (BUTTON_PLAYPAUSE | BUTTON_REL)
#define BTN_STOP       (BUTTON_PLAYPAUSE | BUTTON_REPEAT)
#define BTN_VOLDOWN    BUTTON_VOL_DOWN
#define BTN_VOLUP      BUTTON_VOL_UP
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT

#elif CONFIG_KEYPAD == SANSA_CONNECT_PAD
#define BTN_MENU       BUTTON_POWER
#define BTN_PAUSE      (BUTTON_SELECT | BUTTON_REL)
#define BTN_STOP       (BUTTON_SELECT | BUTTON_REPEAT)
#define BTN_VOLDOWN    BUTTON_VOL_DOWN
#define BTN_VOLUP      BUTTON_VOL_UP
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT
#elif CONFIG_KEYPAD == SAMSUNG_YPR0_PAD
#define BTN_MENU       BUTTON_MENU
#define BTN_PAUSE      BUTTON_SELECT
#define BTN_STOP       BUTTON_POWER
#define BTN_VOLDOWN    BUTTON_DOWN
#define BTN_VOLUP      BUTTON_UP
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT

#elif CONFIG_KEYPAD == HM60X_PAD
#define BTN_MENU       BUTTON_POWER
#define BTN_PAUSE      BUTTON_SELECT
#define BTN_STOP       (BUTTON_SELECT | BUTTON_POWER)
#define BTN_VOLDOWN    (BUTTON_POWER | BUTTON_DOWN)
#define BTN_VOLUP      (BUTTON_POWER | BUTTON_UP)
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT

#elif CONFIG_KEYPAD == HM801_PAD
#define BTN_MENU       BUTTON_POWER
#define BTN_PAUSE      BUTTON_PLAY
#define BTN_STOP       (BUTTON_POWER | BUTTON_PLAY)
#define BTN_VOLDOWN    (BUTTON_POWER | BUTTON_DOWN)
#define BTN_VOLUP      (BUTTON_POWER | BUTTON_UP)
#define BTN_RW         BUTTON_PREV
#define BTN_FF         BUTTON_NEXT

#elif CONFIG_KEYPAD == SONY_NWZ_PAD
#define BTN_MENU       BUTTON_BACK
#define BTN_PAUSE      BUTTON_PLAY
#define BTN_STOP       BUTTON_POWER
#define BTN_VOLDOWN    BUTTON_UP
#define BTN_VOLUP      BUTTON_DOWN
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT

#elif CONFIG_KEYPAD == CREATIVE_ZEN_PAD
#define BTN_MENU       BUTTON_MENU
#define BTN_PAUSE      BUTTON_PLAYPAUSE
#define BTN_STOP       BUTTON_BACK
#define BTN_VOLDOWN    BUTTON_DOWN
#define BTN_VOLUP      BUTTON_UP
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT

#elif CONFIG_KEYPAD == DX50_PAD
#define BTN_MENU       BUTTON_POWER
#define BTN_VOLDOWN    BUTTON_VOL_DOWN
#define BTN_VOLUP      BUTTON_VOL_UP
#define BTN_RW         BUTTON_LEFT
#define BTN_FF         BUTTON_RIGHT
#define BTN_PAUSE      BUTTON_PLAY
#define BTN_STOP       (BUTTON_PLAY|BUTTON_REPEAT)

#else
#error No keymap defined!
#endif

#ifdef HAVE_TOUCHSCREEN
#ifndef BTN_MENU
#define BTN_MENU      (BUTTON_TOPRIGHT|BUTTON_REL)
#endif
#ifndef BTN_STOP
#define BTN_STOP       BUTTON_TOPLEFT
#endif
#ifndef BTN_PAUSE
#define BTN_PAUSE      BUTTON_CENTER
#endif
#ifndef BTN_VOLDOWN
#define BTN_VOLDOWN    BUTTON_BOTTOMMIDDLE
#endif
#ifndef BTN_VOLUP
#define BTN_VOLUP      BUTTON_TOPMIDDLE
#endif
#ifndef BTN_RW
#define BTN_RW         BUTTON_MIDLEFT
#endif
#ifndef BTN_FF
#define BTN_FF         BUTTON_MIDRIGHT
#endif
#endif

